# Generated by Django 5.1.4 on 2026-06-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_date', models.DateField()),
                ('lesson_number', models.DecimalField(decimal_places=1, max_digits=5)),
                ('lesson_duration_minutes', models.IntegerField()),
                ('lesson_type', models.TextField()),
                ('record_url', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('submitted_by_token', models.TextField()),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons', to='groups.group')),
                ('original_teacher', models.ForeignKey(blank=True, db_column='original_teacher_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons_as_original', to='teachers.teacher')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons', to='teachers.teacher')),
            ],
            options={
                'db_table': 'lessons',
                'managed': True,
            },
        ),
        # lesson_attendance имеет составной PK (lesson_id, student_id).
        # Django 5.1 не выражает составной PK нативно (CompositePrimaryKey — c 5.2),
        # поэтому state описывает «обычную» модель, а БД создаётся точным RunSQL.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='LessonAttendance',
                    fields=[
                        ('lesson', models.ForeignKey(db_column='lesson_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attendance', serialize=False, to='lessons.lesson')),
                        ('present', models.BooleanField()),
                        ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance', to='students.student')),
                    ],
                    options={
                        'db_table': 'lesson_attendance',
                        'managed': True,
                    },
                ),
                migrations.AddIndex(
                    model_name='lessonattendance',
                    index=models.Index(fields=['student'], name='lesson_attendance_student_idx'),
                ),
                migrations.AlterUniqueTogether(
                    name='lessonattendance',
                    unique_together={('lesson', 'student')},
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE lesson_attendance (
                          lesson_id  integer NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
                          student_id integer NOT NULL REFERENCES students(id),
                          present    boolean NOT NULL,
                          PRIMARY KEY (lesson_id, student_id)
                        );
                        CREATE INDEX lesson_attendance_student_idx
                          ON lesson_attendance (student_id);
                    """,
                    reverse_sql="DROP TABLE lesson_attendance;",
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'lesson_date'], name='lessons_group_date_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'lesson_date'], name='lessons_teacher_date_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['-lesson_date', '-id'], name='lessons_date_desc_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('lesson_date', 'group', 'lesson_number', 'submitted_by_token'), name='lessons_natural_key'),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lessons ALTER COLUMN submitted_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE lessons ALTER COLUMN submitted_at DROP DEFAULT;",
        ),
    ]
