# Generated by Django 5.2.15 on 2026-07-06 08:00

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupevent_groupscheduleslotevent_and_more'),
        ('lessons', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('students', '0002_remove_student_consent_at_remove_student_consent_by_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAttendanceEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('present', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('lesson_date', models.DateField()),
                ('lesson_number', models.DecimalField(decimal_places=1, max_digits=5)),
                ('lesson_duration_minutes', models.IntegerField()),
                ('lesson_type', models.TextField()),
                ('record_url', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('submitted_by_token', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonevent" ("group_id", "id", "lesson_date", "lesson_duration_minutes", "lesson_number", "lesson_type", "original_teacher_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "record_url", "submitted_at", "submitted_by_token", "teacher_id") VALUES (NEW."group_id", NEW."id", NEW."lesson_date", NEW."lesson_duration_minutes", NEW."lesson_number", NEW."lesson_type", NEW."original_teacher_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."record_url", NEW."submitted_at", NEW."submitted_by_token", NEW."teacher_id"); RETURN NULL;', hash='8bd3a72ac41df755735845302f1c9c0a69584019', operation='INSERT', pgid='pgtrigger_insert_insert_cb183', table='lessons', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lessons_lessonevent" ("group_id", "id", "lesson_date", "lesson_duration_minutes", "lesson_number", "lesson_type", "original_teacher_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "record_url", "submitted_at", "submitted_by_token", "teacher_id") VALUES (NEW."group_id", NEW."id", NEW."lesson_date", NEW."lesson_duration_minutes", NEW."lesson_number", NEW."lesson_type", NEW."original_teacher_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."record_url", NEW."submitted_at", NEW."submitted_by_token", NEW."teacher_id"); RETURN NULL;', hash='853de3f6643401ee2abaa560ba81d9b481af4834', operation='UPDATE', pgid='pgtrigger_update_update_6db5b', table='lessons', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonevent" ("group_id", "id", "lesson_date", "lesson_duration_minutes", "lesson_number", "lesson_type", "original_teacher_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "record_url", "submitted_at", "submitted_by_token", "teacher_id") VALUES (OLD."group_id", OLD."id", OLD."lesson_date", OLD."lesson_duration_minutes", OLD."lesson_number", OLD."lesson_type", OLD."original_teacher_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."record_url", OLD."submitted_at", OLD."submitted_by_token", OLD."teacher_id"); RETURN NULL;', hash='60093691896289f75108ff9b7aa4299ec1e440fb', operation='DELETE', pgid='pgtrigger_delete_delete_288ee', table='lessons', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonattendanceevent" ("lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id") VALUES (NEW."lesson_id", _pgh_attach_context(), NOW(), \'insert\', NEW."lesson_id", NEW."present", NEW."student_id"); RETURN NULL;', hash='e3e0217ae45ea3fcd58face138eee1cdf374fe5f', operation='INSERT', pgid='pgtrigger_insert_insert_c494d', table='lesson_attendance', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lessons_lessonattendanceevent" ("lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id") VALUES (NEW."lesson_id", _pgh_attach_context(), NOW(), \'update\', NEW."lesson_id", NEW."present", NEW."student_id"); RETURN NULL;', hash='df9894cc518558e63dc7a805d6270a02aca9798b', operation='UPDATE', pgid='pgtrigger_update_update_e0930', table='lesson_attendance', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonattendanceevent" ("lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id") VALUES (OLD."lesson_id", _pgh_attach_context(), NOW(), \'delete\', OLD."lesson_id", OLD."present", OLD."student_id"); RETURN NULL;', hash='67f1f6f9fb1fce0cf3b7ed40041f8286cbbae8d3', operation='DELETE', pgid='pgtrigger_delete_delete_cd3ea', table='lesson_attendance', when='AFTER')),
        ),
        migrations.AddField(
            model_name='lessonattendanceevent',
            name='lesson',
            field=models.ForeignKey(db_column='lesson_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', serialize=False, to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='lessonattendanceevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='lessonattendanceevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='lessons.lessonattendance'),
        ),
        migrations.AddField(
            model_name='lessonattendanceevent',
            name='student',
            field=models.ForeignKey(db_column='student_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='students.student'),
        ),
        migrations.AddField(
            model_name='lessonevent',
            name='group',
            field=models.ForeignKey(db_column='group_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='groups.group'),
        ),
        migrations.AddField(
            model_name='lessonevent',
            name='original_teacher',
            field=models.ForeignKey(blank=True, db_column='original_teacher_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='lessonevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='lessonevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='lessonevent',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='teachers.teacher'),
        ),
    ]
