# Generated by Django 5.2.15 on 2026-07-16 19:10

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessonattendanceevent_lessonevent_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='lessonattendance',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lessonattendance',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lessonattendance',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='lessonattendance',
            name='burned_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonattendanceevent',
            name='burned_at',
            field=models.DateField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonattendanceevent" ("burned_at", "lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id") VALUES (NEW."burned_at", NEW."lesson_id", _pgh_attach_context(), NOW(), \'insert\', NEW."lesson_id", NEW."present", NEW."student_id"); RETURN NULL;', hash='85fc2d40b30682f3299bb085cef4bdcf3c4e753c', operation='INSERT', pgid='pgtrigger_insert_insert_c494d', table='lesson_attendance', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lessons_lessonattendanceevent" ("burned_at", "lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id") VALUES (NEW."burned_at", NEW."lesson_id", _pgh_attach_context(), NOW(), \'update\', NEW."lesson_id", NEW."present", NEW."student_id"); RETURN NULL;', hash='cfc671ce2c41a4dedd80e779e10d869a000453ce', operation='UPDATE', pgid='pgtrigger_update_update_e0930', table='lesson_attendance', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonattendanceevent" ("burned_at", "lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id") VALUES (OLD."burned_at", OLD."lesson_id", _pgh_attach_context(), NOW(), \'delete\', OLD."lesson_id", OLD."present", OLD."student_id"); RETURN NULL;', hash='983826959a47ce928eb95901b44f822f6f794b0f', operation='DELETE', pgid='pgtrigger_delete_delete_cd3ea', table='lesson_attendance', when='AFTER')),
        ),
    ]
