# Generated by Django 5.2.15 on 2026-07-18 19:04

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lessonattendance_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='lessonattendance',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lessonattendance',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lessonattendance',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='lessonattendance',
            name='burned_at',
        ),
        migrations.RemoveField(
            model_name='lessonattendanceevent',
            name='burned_at',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonattendanceevent" ("lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id") VALUES (NEW."lesson_id", _pgh_attach_context(), NOW(), \'insert\', NEW."lesson_id", NEW."present", NEW."student_id"); RETURN NULL;', hash='e3e0217ae45ea3fcd58face138eee1cdf374fe5f', operation='INSERT', pgid='pgtrigger_insert_insert_c494d', table='lesson_attendance', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lessons_lessonattendanceevent" ("lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id") VALUES (NEW."lesson_id", _pgh_attach_context(), NOW(), \'update\', NEW."lesson_id", NEW."present", NEW."student_id"); RETURN NULL;', hash='df9894cc518558e63dc7a805d6270a02aca9798b', operation='UPDATE', pgid='pgtrigger_update_update_e0930', table='lesson_attendance', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonattendanceevent" ("lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id") VALUES (OLD."lesson_id", _pgh_attach_context(), NOW(), \'delete\', OLD."lesson_id", OLD."present", OLD."student_id"); RETURN NULL;', hash='67f1f6f9fb1fce0cf3b7ed40041f8286cbbae8d3', operation='DELETE', pgid='pgtrigger_delete_delete_cd3ea', table='lesson_attendance', when='AFTER')),
        ),
    ]
