# Generated by Django 5.2.15 on 2026-07-22 23:51

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_lessonattendance_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='lessonattendance',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lessonattendance',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lessonattendance',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='lessonattendance',
            name='is_free',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='lessonattendanceevent',
            name='is_free',
            field=models.BooleanField(db_default=False, default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonattendanceevent" ("is_free", "lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id") VALUES (NEW."is_free", NEW."lesson_id", _pgh_attach_context(), NOW(), \'insert\', NEW."lesson_id", NEW."present", NEW."student_id"); RETURN NULL;', hash='a040309666089baa3a244fdee930ac1a667c2c73', operation='INSERT', pgid='pgtrigger_insert_insert_c494d', table='lesson_attendance', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lessons_lessonattendanceevent" ("is_free", "lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id") VALUES (NEW."is_free", NEW."lesson_id", _pgh_attach_context(), NOW(), \'update\', NEW."lesson_id", NEW."present", NEW."student_id"); RETURN NULL;', hash='615faeb5d3b5f8a159ebfd48d7096d42b469b8a1', operation='UPDATE', pgid='pgtrigger_update_update_e0930', table='lesson_attendance', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonattendanceevent" ("is_free", "lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id") VALUES (OLD."is_free", OLD."lesson_id", _pgh_attach_context(), NOW(), \'delete\', OLD."lesson_id", OLD."present", OLD."student_id"); RETURN NULL;', hash='82c763eb73551f5d87da9e7d5115bf193e51cd67', operation='DELETE', pgid='pgtrigger_delete_delete_cd3ea', table='lesson_attendance', when='AFTER')),
        ),
    ]
