# Generated by Django 5.2.15 on 2026-07-23 08:06

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_remove_lessonattendance_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='lessonattendance',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lessonattendance',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lessonattendance',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='lessonattendance',
            name='unpaid_skip',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='lessonattendanceevent',
            name='unpaid_skip',
            field=models.BooleanField(db_default=False, default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonattendanceevent" ("is_free", "lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id", "unpaid_skip") VALUES (NEW."is_free", NEW."lesson_id", _pgh_attach_context(), NOW(), \'insert\', NEW."lesson_id", NEW."present", NEW."student_id", NEW."unpaid_skip"); RETURN NULL;', hash='ead6d167d6f9c929d627705731cfe8d1103102df', operation='INSERT', pgid='pgtrigger_insert_insert_c494d', table='lesson_attendance', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lessons_lessonattendanceevent" ("is_free", "lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id", "unpaid_skip") VALUES (NEW."is_free", NEW."lesson_id", _pgh_attach_context(), NOW(), \'update\', NEW."lesson_id", NEW."present", NEW."student_id", NEW."unpaid_skip"); RETURN NULL;', hash='914313bd10f73e0a5e4e0ceb993563b9dcbe2499', operation='UPDATE', pgid='pgtrigger_update_update_e0930', table='lesson_attendance', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonattendance',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonattendanceevent" ("is_free", "lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present", "student_id", "unpaid_skip") VALUES (OLD."is_free", OLD."lesson_id", _pgh_attach_context(), NOW(), \'delete\', OLD."lesson_id", OLD."present", OLD."student_id", OLD."unpaid_skip"); RETURN NULL;', hash='f783726b20dfe96520321e5e47ac68c9c1614c06', operation='DELETE', pgid='pgtrigger_delete_delete_cd3ea', table='lesson_attendance', when='AFTER')),
        ),
    ]
