# Generated by Django 5.2.15 on 2026-07-23 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_group_insert_insert_and_more'),
        ('lessons', '0006_remove_lessonattendance_insert_insert_and_more'),
        ('students', '0012_student_manager_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSkip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_number', models.DecimalField(decimal_places=1, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_skips', to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_skips', to='students.student')),
            ],
            options={
                'db_table': 'lesson_skips',
                'managed': True,
                'indexes': [models.Index(fields=['group', 'lesson_number'], name='lesson_skips_group_num_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'student', 'lesson_number'), name='lesson_skips_group_student_number_key')],
            },
        ),
    ]
