# Generated by Django 5.2.15 on 2026-07-24 13:07

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_group_insert_insert_and_more'),
        ('lessons', '0007_lessonskip'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('students', '0015_drop_not_enrolled_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSkipEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('lesson_number', models.DecimalField(decimal_places=1, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonskip',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonskipevent" ("created_at", "group_id", "id", "lesson_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id") VALUES (NEW."created_at", NEW."group_id", NEW."id", NEW."lesson_number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."student_id"); RETURN NULL;', hash='bfe44ead42fb9c7ceb5f7114e4c7184c3cfacf62', operation='INSERT', pgid='pgtrigger_insert_insert_8b2fb', table='lesson_skips', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonskip',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lessons_lessonskipevent" ("created_at", "group_id", "id", "lesson_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id") VALUES (NEW."created_at", NEW."group_id", NEW."id", NEW."lesson_number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."student_id"); RETURN NULL;', hash='ead1813c6ab01600942f2ff74edde28319af34df', operation='UPDATE', pgid='pgtrigger_update_update_cccff', table='lesson_skips', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lessonskip',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonskipevent" ("created_at", "group_id", "id", "lesson_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id") VALUES (OLD."created_at", OLD."group_id", OLD."id", OLD."lesson_number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."student_id"); RETURN NULL;', hash='0994dfa1db1141c4ecacaffadb1db6527b84c91b', operation='DELETE', pgid='pgtrigger_delete_delete_f729d', table='lesson_skips', when='AFTER')),
        ),
        migrations.AddField(
            model_name='lessonskipevent',
            name='group',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='groups.group'),
        ),
        migrations.AddField(
            model_name='lessonskipevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='lessonskipevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='lessons.lessonskip'),
        ),
        migrations.AddField(
            model_name='lessonskipevent',
            name='student',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='students.student'),
        ),
    ]
