# Generated by Django 5.2.15 on 2026-08-01 22:59

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove_group_insert_insert_and_more'),
        ('lessons', '0008_track_lesson_skip'),
        ('teachers', '0002_teacherevent_teacher_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='lesson',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lesson',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='lesson',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='lesson',
            name='submission_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonevent',
            name='submission_key',
            field=models.TextField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonevent" ("group_id", "id", "lesson_date", "lesson_duration_minutes", "lesson_number", "lesson_type", "original_teacher_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "record_url", "submission_key", "submitted_at", "submitted_by_token", "teacher_id") VALUES (NEW."group_id", NEW."id", NEW."lesson_date", NEW."lesson_duration_minutes", NEW."lesson_number", NEW."lesson_type", NEW."original_teacher_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."record_url", NEW."submission_key", NEW."submitted_at", NEW."submitted_by_token", NEW."teacher_id"); RETURN NULL;', hash='6ff1e5d4a19f901ed16ad312a3f5164778230e99', operation='INSERT', pgid='pgtrigger_insert_insert_cb183', table='lessons', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "lessons_lessonevent" ("group_id", "id", "lesson_date", "lesson_duration_minutes", "lesson_number", "lesson_type", "original_teacher_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "record_url", "submission_key", "submitted_at", "submitted_by_token", "teacher_id") VALUES (NEW."group_id", NEW."id", NEW."lesson_date", NEW."lesson_duration_minutes", NEW."lesson_number", NEW."lesson_type", NEW."original_teacher_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."record_url", NEW."submission_key", NEW."submitted_at", NEW."submitted_by_token", NEW."teacher_id"); RETURN NULL;', hash='caa4821a63811f30fbc8ba265b3f385a4e8cf4c2', operation='UPDATE', pgid='pgtrigger_update_update_6db5b', table='lessons', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='lesson',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "lessons_lessonevent" ("group_id", "id", "lesson_date", "lesson_duration_minutes", "lesson_number", "lesson_type", "original_teacher_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "record_url", "submission_key", "submitted_at", "submitted_by_token", "teacher_id") VALUES (OLD."group_id", OLD."id", OLD."lesson_date", OLD."lesson_duration_minutes", OLD."lesson_number", OLD."lesson_type", OLD."original_teacher_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."record_url", OLD."submission_key", OLD."submitted_at", OLD."submitted_by_token", OLD."teacher_id"); RETURN NULL;', hash='b371c57c2cc134413094df952850bd3171ed4a76', operation='DELETE', pgid='pgtrigger_delete_delete_288ee', table='lessons', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('submission_key__isnull', False)), fields=('group', 'submission_key'), name='lessons_submission_key_unique'),
        ),
    ]
