# Generated by Django 5.1.4 on 2026-06-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_students', models.IntegerField()),
                ('present_count', models.IntegerField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lesson', models.OneToOneField(db_column='lesson_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='payroll', to='lessons.lesson')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='payroll_entries', to='teachers.teacher')),
            ],
            options={
                'db_table': 'payroll',
                'managed': True,
                'indexes': [models.Index(fields=['teacher', 'lesson'], name='payroll_teacher_lesson_idx'), models.Index(fields=['lesson'], name='payroll_lesson_id_idx')],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE payroll ALTER COLUMN penalty SET DEFAULT 0;",
            reverse_sql="ALTER TABLE payroll ALTER COLUMN penalty DROP DEFAULT;",
        ),
    ]
