# Generated by Django 5.2.15 on 2026-07-06 08:00

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessonattendanceevent_lessonevent_and_more'),
        ('payroll', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('total_students', models.IntegerField()),
                ('present_count', models.IntegerField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payroll',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payroll_payrollevent" ("id", "lesson_id", "payment", "penalty", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present_count", "teacher_id", "total_students") VALUES (NEW."id", NEW."lesson_id", NEW."payment", NEW."penalty", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."present_count", NEW."teacher_id", NEW."total_students"); RETURN NULL;', hash='64bf448e995b542376427e635d6f3660e2ed7846', operation='INSERT', pgid='pgtrigger_insert_insert_6c31e', table='payroll', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payroll',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payroll_payrollevent" ("id", "lesson_id", "payment", "penalty", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present_count", "teacher_id", "total_students") VALUES (NEW."id", NEW."lesson_id", NEW."payment", NEW."penalty", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."present_count", NEW."teacher_id", NEW."total_students"); RETURN NULL;', hash='75ad7ac93a3a50bc4bf642d1f9ae9e29b76bda3c', operation='UPDATE', pgid='pgtrigger_update_update_71492', table='payroll', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payroll',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payroll_payrollevent" ("id", "lesson_id", "payment", "penalty", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present_count", "teacher_id", "total_students") VALUES (OLD."id", OLD."lesson_id", OLD."payment", OLD."penalty", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."present_count", OLD."teacher_id", OLD."total_students"); RETURN NULL;', hash='ebbd7aa319dbf831c7146cc593622d5d02dec238', operation='DELETE', pgid='pgtrigger_delete_delete_6eb83', table='payroll', when='AFTER')),
        ),
        migrations.AddField(
            model_name='payrollevent',
            name='lesson',
            field=models.ForeignKey(db_column='lesson_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='payrollevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='payrollevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='payroll.payroll'),
        ),
        migrations.AddField(
            model_name='payrollevent',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='teachers.teacher'),
        ),
    ]
