# Generated by Django 5.2.15 on 2026-07-16 23:18

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollevent_payroll_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='payroll',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payroll',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payroll',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='payroll',
            name='burn_surcharge_amount',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='burn_surcharge_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollevent',
            name='burn_surcharge_amount',
            field=models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollevent',
            name='burn_surcharge_at',
            field=models.DateField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payroll',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payroll_payrollevent" ("burn_surcharge_amount", "burn_surcharge_at", "id", "lesson_id", "payment", "penalty", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present_count", "teacher_id", "total_students") VALUES (NEW."burn_surcharge_amount", NEW."burn_surcharge_at", NEW."id", NEW."lesson_id", NEW."payment", NEW."penalty", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."present_count", NEW."teacher_id", NEW."total_students"); RETURN NULL;', hash='314b83c3eb7ad2bd1660245fc974a4e49c4d6d5e', operation='INSERT', pgid='pgtrigger_insert_insert_6c31e', table='payroll', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payroll',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payroll_payrollevent" ("burn_surcharge_amount", "burn_surcharge_at", "id", "lesson_id", "payment", "penalty", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present_count", "teacher_id", "total_students") VALUES (NEW."burn_surcharge_amount", NEW."burn_surcharge_at", NEW."id", NEW."lesson_id", NEW."payment", NEW."penalty", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."present_count", NEW."teacher_id", NEW."total_students"); RETURN NULL;', hash='ac0574ba78df58f272e682b0430c29428a965250', operation='UPDATE', pgid='pgtrigger_update_update_71492', table='payroll', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payroll',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payroll_payrollevent" ("burn_surcharge_amount", "burn_surcharge_at", "id", "lesson_id", "payment", "penalty", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present_count", "teacher_id", "total_students") VALUES (OLD."burn_surcharge_amount", OLD."burn_surcharge_at", OLD."id", OLD."lesson_id", OLD."payment", OLD."penalty", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."present_count", OLD."teacher_id", OLD."total_students"); RETURN NULL;', hash='eb59ebe85a526da0dd536788c1783bd109ca2d50', operation='DELETE', pgid='pgtrigger_delete_delete_6eb83', table='payroll', when='AFTER')),
        ),
    ]
