# Generated by Django 5.2.15 on 2026-07-18 19:07

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_payroll_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='payroll',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payroll',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payroll',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='burn_surcharge_amount',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='burn_surcharge_at',
        ),
        migrations.RemoveField(
            model_name='payrollevent',
            name='burn_surcharge_amount',
        ),
        migrations.RemoveField(
            model_name='payrollevent',
            name='burn_surcharge_at',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payroll',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payroll_payrollevent" ("id", "lesson_id", "payment", "penalty", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present_count", "teacher_id", "total_students") VALUES (NEW."id", NEW."lesson_id", NEW."payment", NEW."penalty", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."present_count", NEW."teacher_id", NEW."total_students"); RETURN NULL;', hash='64bf448e995b542376427e635d6f3660e2ed7846', operation='INSERT', pgid='pgtrigger_insert_insert_6c31e', table='payroll', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payroll',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payroll_payrollevent" ("id", "lesson_id", "payment", "penalty", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present_count", "teacher_id", "total_students") VALUES (NEW."id", NEW."lesson_id", NEW."payment", NEW."penalty", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."present_count", NEW."teacher_id", NEW."total_students"); RETURN NULL;', hash='75ad7ac93a3a50bc4bf642d1f9ae9e29b76bda3c', operation='UPDATE', pgid='pgtrigger_update_update_71492', table='payroll', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payroll',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payroll_payrollevent" ("id", "lesson_id", "payment", "penalty", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "present_count", "teacher_id", "total_students") VALUES (OLD."id", OLD."lesson_id", OLD."payment", OLD."penalty", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."present_count", OLD."teacher_id", OLD."total_students"); RETURN NULL;', hash='ebbd7aa319dbf831c7146cc593622d5d02dec238', operation='DELETE', pgid='pgtrigger_delete_delete_6eb83', table='payroll', when='AFTER')),
        ),
    ]
