# Generated by Django 5.2.15 on 2026-07-15 20:11

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_lessonattendanceevent_lessonevent_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('students', '0008_studentcomment'),
        ('teachers', '0002_teacherevent_teacher_insert_insert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraLessonAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fact_lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_lesson_assignment', to='lessons.lesson')),
                ('missed_lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_lesson_assignments', to='lessons.lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_lesson_assignments', to='teachers.teacher')),
            ],
            options={
                'db_table': 'extra_lesson_assignments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExtraLessonAssignmentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fact_lesson', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='lessons.lesson')),
                ('missed_lesson', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='lessons.lesson')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='extra_lessons.extralessonassignment')),
                ('teacher', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraLessonParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='extra_lessons.extralessonassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_lesson_participations', to='students.student')),
            ],
            options={
                'db_table': 'extra_lesson_participants',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='extralessonassignment',
            name='students',
            field=models.ManyToManyField(related_name='extra_lesson_assignments', through='extra_lessons.ExtraLessonParticipant', to='students.student'),
        ),
        migrations.CreateModel(
            name='ExtraLessonParticipantEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('assignment', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='extra_lessons.extralessonassignment')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='extra_lessons.extralessonparticipant')),
                ('student', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='extralessonparticipant',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='extra_lesson_participants_assignment_student_key'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='extralessonparticipant',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "extra_lessons_extralessonparticipantevent" ("assignment_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id") VALUES (NEW."assignment_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."student_id"); RETURN NULL;', hash='c29b0c3c11e5932af536f211558afc4e2be5892c', operation='INSERT', pgid='pgtrigger_insert_insert_aa52e', table='extra_lesson_participants', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='extralessonparticipant',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "extra_lessons_extralessonparticipantevent" ("assignment_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id") VALUES (NEW."assignment_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."student_id"); RETURN NULL;', hash='4241f43bb60312c960e44a6fe38b7ca91831dd54', operation='UPDATE', pgid='pgtrigger_update_update_06e5e', table='extra_lesson_participants', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='extralessonparticipant',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "extra_lessons_extralessonparticipantevent" ("assignment_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id") VALUES (OLD."assignment_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."student_id"); RETURN NULL;', hash='872680ff62b403a582ccfea3c555b9c1b0ca5589', operation='DELETE', pgid='pgtrigger_delete_delete_8369e', table='extra_lesson_participants', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='extralessonassignment',
            index=models.Index(fields=['teacher', 'scheduled_date'], name='ela_teacher_date_idx'),
        ),
        migrations.AddIndex(
            model_name='extralessonassignment',
            index=models.Index(fields=['missed_lesson'], name='ela_missed_lesson_idx'),
        ),
        migrations.AddConstraint(
            model_name='extralessonassignment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['scheduled', 'done', 'cancelled'])), name='extra_lesson_assignments_status_check'),
        ),
        migrations.AddConstraint(
            model_name='extralessonassignment',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__in', (30, 45, 60, 90))), name='extra_lesson_assignments_duration_check'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='extralessonassignment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "extra_lessons_extralessonassignmentevent" ("created_at", "duration_minutes", "fact_lesson_id", "id", "missed_lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "status", "teacher_id") VALUES (NEW."created_at", NEW."duration_minutes", NEW."fact_lesson_id", NEW."id", NEW."missed_lesson_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."scheduled_date", NEW."scheduled_time", NEW."status", NEW."teacher_id"); RETURN NULL;', hash='c1658258fdca68ad21eb96954199871e54e3e91a', operation='INSERT', pgid='pgtrigger_insert_insert_f19ef', table='extra_lesson_assignments', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='extralessonassignment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "extra_lessons_extralessonassignmentevent" ("created_at", "duration_minutes", "fact_lesson_id", "id", "missed_lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "status", "teacher_id") VALUES (NEW."created_at", NEW."duration_minutes", NEW."fact_lesson_id", NEW."id", NEW."missed_lesson_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."scheduled_date", NEW."scheduled_time", NEW."status", NEW."teacher_id"); RETURN NULL;', hash='1f7f92da19239c4362f714454ce79cbe4f9356a2', operation='UPDATE', pgid='pgtrigger_update_update_f32b7', table='extra_lesson_assignments', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='extralessonassignment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "extra_lessons_extralessonassignmentevent" ("created_at", "duration_minutes", "fact_lesson_id", "id", "missed_lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "status", "teacher_id") VALUES (OLD."created_at", OLD."duration_minutes", OLD."fact_lesson_id", OLD."id", OLD."missed_lesson_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."scheduled_date", OLD."scheduled_time", OLD."status", OLD."teacher_id"); RETURN NULL;', hash='75963205f8e1c89ebfdd95f4d0c6782f647244e1', operation='DELETE', pgid='pgtrigger_delete_delete_44a61', table='extra_lesson_assignments', when='AFTER')),
        ),
    ]
