# Generated by Django 5.2.15 on 2026-07-18 00:54

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_lessons', '0001_initial'),
        ('lessons', '0003_remove_lessonattendance_insert_insert_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('students', '0011_drop_frozen_month'),
        ('teachers', '0002_teacherevent_teacher_insert_insert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceResolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absence_resolutions', to='teachers.teacher')),
                ('fact_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absence_resolution_facts', to='lessons.lesson')),
                ('missed_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_resolutions', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_resolutions', to='students.student')),
            ],
            options={
                'db_table': 'absence_resolutions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AbsenceResolutionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='teachers.teacher')),
                ('fact_lesson', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='lessons.lesson')),
                ('missed_lesson', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='lessons.lesson')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='extra_lessons.absenceresolution')),
                ('student', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='absenceresolution',
            index=models.Index(fields=['status'], name='ar_status_idx'),
        ),
        migrations.AddIndex(
            model_name='absenceresolution',
            index=models.Index(fields=['missed_lesson'], name='ar_missed_lesson_idx'),
        ),
        migrations.AddIndex(
            model_name='absenceresolution',
            index=models.Index(fields=['assigned_teacher', 'scheduled_date'], name='ar_teacher_date_idx'),
        ),
        migrations.AddIndex(
            model_name='absenceresolution',
            index=models.Index(fields=['student'], name='ar_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='absenceresolution',
            constraint=models.UniqueConstraint(fields=('missed_lesson', 'student'), name='absence_resolutions_missed_student_key'),
        ),
        migrations.AddConstraint(
            model_name='absenceresolution',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['scheduled', 'done', 'cancelled'])), name='absence_resolutions_status_check'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='absenceresolution',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "extra_lessons_absenceresolutionevent" ("assigned_teacher_id", "created_at", "duration_minutes", "fact_lesson_id", "id", "missed_lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "status", "student_id") VALUES (NEW."assigned_teacher_id", NEW."created_at", NEW."duration_minutes", NEW."fact_lesson_id", NEW."id", NEW."missed_lesson_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."scheduled_date", NEW."scheduled_time", NEW."status", NEW."student_id"); RETURN NULL;', hash='48e74fb098ed30d72769be2e1eac2e17eed21bff', operation='INSERT', pgid='pgtrigger_insert_insert_f67c0', table='absence_resolutions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='absenceresolution',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "extra_lessons_absenceresolutionevent" ("assigned_teacher_id", "created_at", "duration_minutes", "fact_lesson_id", "id", "missed_lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "status", "student_id") VALUES (NEW."assigned_teacher_id", NEW."created_at", NEW."duration_minutes", NEW."fact_lesson_id", NEW."id", NEW."missed_lesson_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."scheduled_date", NEW."scheduled_time", NEW."status", NEW."student_id"); RETURN NULL;', hash='8b55aa13efbf98eb729db9f5359e9f591f2c7dba', operation='UPDATE', pgid='pgtrigger_update_update_2b9ae', table='absence_resolutions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='absenceresolution',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "extra_lessons_absenceresolutionevent" ("assigned_teacher_id", "created_at", "duration_minutes", "fact_lesson_id", "id", "missed_lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "status", "student_id") VALUES (OLD."assigned_teacher_id", OLD."created_at", OLD."duration_minutes", OLD."fact_lesson_id", OLD."id", OLD."missed_lesson_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."scheduled_date", OLD."scheduled_time", OLD."status", OLD."student_id"); RETURN NULL;', hash='46bf39ce1e65770c93380422b591c4c32e37658b', operation='DELETE', pgid='pgtrigger_delete_delete_6f9e4', table='absence_resolutions', when='AFTER')),
        ),
    ]
