# Generated by Django 5.2.15 on 2026-07-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_lessons', '0003_migrate_group_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extralessonparticipantevent',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='extralessonassignmentevent',
            name='pgh_obj',
        ),
        migrations.RemoveField(
            model_name='extralessonparticipant',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='extralessonassignmentevent',
            name='fact_lesson',
        ),
        migrations.RemoveField(
            model_name='extralessonassignmentevent',
            name='missed_lesson',
        ),
        migrations.RemoveField(
            model_name='extralessonassignmentevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='extralessonassignmentevent',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='extralessonparticipant',
            name='student',
        ),
        migrations.RemoveField(
            model_name='extralessonparticipantevent',
            name='pgh_obj',
        ),
        migrations.RemoveField(
            model_name='extralessonparticipantevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='extralessonparticipantevent',
            name='student',
        ),
        migrations.DeleteModel(
            name='ExtraLessonAssignment',
        ),
        migrations.DeleteModel(
            name='ExtraLessonAssignmentEvent',
        ),
        migrations.DeleteModel(
            name='ExtraLessonParticipant',
        ),
        migrations.DeleteModel(
            name='ExtraLessonParticipantEvent',
        ),
    ]
