# Generated by Django 5.2.15 on 2026-07-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_lessons', '0004_remove_extralessonparticipantevent_assignment_and_more'),
        ('lessons', '0003_remove_lessonattendance_insert_insert_and_more'),
        ('students', '0011_drop_frozen_month'),
        ('teachers', '0002_teacherevent_teacher_insert_insert_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='absenceresolution',
            name='absence_resolutions_missed_student_key',
        ),
        migrations.AddConstraint(
            model_name='absenceresolution',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('missed_lesson', 'student'), name='absence_resolutions_missed_student_key'),
        ),
    ]
