# Generated by Django 5.2.15 on 2026-07-18 12:49

from django.db import migrations, models

from apps.extra_lessons._migration_helpers import remap_statuses_1b


def _forward(apps, schema_editor):
    remap_statuses_1b(schema_editor.connection)


class Migration(migrations.Migration):

    dependencies = [
        ('extra_lessons', '0005_remove_absenceresolution_absence_resolutions_missed_student_key_and_more'),
        ('lessons', '0003_remove_lessonattendance_insert_insert_and_more'),
        ('students', '0011_drop_frozen_month'),
        ('teachers', '0002_teacherevent_teacher_insert_insert_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='absenceresolution',
            name='absence_resolutions_status_check',
        ),
        migrations.RemoveConstraint(
            model_name='absenceresolution',
            name='absence_resolutions_missed_student_key',
        ),
        # Данные: после снятия старого CHECK/uniq (выше) и ДО создания новых
        # (ниже) — удалить cancelled-строки и переименовать scheduled/done.
        migrations.RunPython(_forward, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='absenceresolution',
            name='status',
            field=models.CharField(default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='absenceresolutionevent',
            name='status',
            field=models.CharField(default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='absenceresolution',
            constraint=models.UniqueConstraint(fields=('missed_lesson', 'student'), name='absence_resolutions_missed_student_key'),
        ),
        migrations.AddConstraint(
            model_name='absenceresolution',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'makeup_scheduled', 'makeup_done'])), name='absence_resolutions_status_check'),
        ),
    ]
