# Generated by Django 5.2.15 on 2026-07-23 02:33

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_lessons', '0010_convert_historical_burned_at'),
        ('groups', '0005_remove_group_insert_insert_and_more'),
        ('lessons', '0005_remove_lessonattendance_insert_insert_and_more'),
        ('students', '0012_student_manager_fk'),
        ('teachers', '0002_teacherevent_teacher_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='absenceresolution',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='absenceresolution',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='absenceresolution',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='absenceresolution',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_resolutions', to='groups.group'),
        ),
        migrations.AddField(
            model_name='absenceresolution',
            name='kind',
            field=models.CharField(db_default='makeup', default='makeup', max_length=16),
        ),
        migrations.AddField(
            model_name='absenceresolutionevent',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='groups.group'),
        ),
        migrations.AddField(
            model_name='absenceresolutionevent',
            name='kind',
            field=models.CharField(db_default='makeup', default='makeup', max_length=16),
        ),
        migrations.AlterField(
            model_name='absenceresolution',
            name='missed_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_resolutions', to='lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='absenceresolutionevent',
            name='missed_lesson',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='lessons.lesson'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='absenceresolution',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "extra_lessons_absenceresolutionevent" ("assigned_teacher_id", "created_at", "duration_minutes", "fact_lesson_id", "group_id", "id", "kind", "missed_lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "status", "student_id") VALUES (NEW."assigned_teacher_id", NEW."created_at", NEW."duration_minutes", NEW."fact_lesson_id", NEW."group_id", NEW."id", NEW."kind", NEW."missed_lesson_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."scheduled_date", NEW."scheduled_time", NEW."status", NEW."student_id"); RETURN NULL;', hash='f31423cc8f4199761fdac7218687de45789c7709', operation='INSERT', pgid='pgtrigger_insert_insert_f67c0', table='absence_resolutions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='absenceresolution',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "extra_lessons_absenceresolutionevent" ("assigned_teacher_id", "created_at", "duration_minutes", "fact_lesson_id", "group_id", "id", "kind", "missed_lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "status", "student_id") VALUES (NEW."assigned_teacher_id", NEW."created_at", NEW."duration_minutes", NEW."fact_lesson_id", NEW."group_id", NEW."id", NEW."kind", NEW."missed_lesson_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."scheduled_date", NEW."scheduled_time", NEW."status", NEW."student_id"); RETURN NULL;', hash='f38e1f67ac85b443a01baf1dec9d29e950ee4e7f', operation='UPDATE', pgid='pgtrigger_update_update_2b9ae', table='absence_resolutions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='absenceresolution',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "extra_lessons_absenceresolutionevent" ("assigned_teacher_id", "created_at", "duration_minutes", "fact_lesson_id", "group_id", "id", "kind", "missed_lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "status", "student_id") VALUES (OLD."assigned_teacher_id", OLD."created_at", OLD."duration_minutes", OLD."fact_lesson_id", OLD."group_id", OLD."id", OLD."kind", OLD."missed_lesson_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."scheduled_date", OLD."scheduled_time", OLD."status", OLD."student_id"); RETURN NULL;', hash='fc54873b125659db1893d4ee1db8d72b108759be', operation='DELETE', pgid='pgtrigger_delete_delete_6f9e4', table='absence_resolutions', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='absenceresolution',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['makeup', 'extra'])), name='absence_resolutions_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='absenceresolution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'makeup'), ('missed_lesson__isnull', False)), models.Q(('kind', 'extra'), ('missed_lesson__isnull', True), ('group__isnull', False)), _connector='OR'), name='absence_resolutions_kind_shape'),
        ),
    ]
