# Generated by Django 5.2.15 on 2026-07-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_lessons', '0012_restore_missed_lesson_cascade'),
        ('groups', '0005_remove_group_insert_insert_and_more'),
        ('lessons', '0005_remove_lessonattendance_insert_insert_and_more'),
        ('students', '0012_student_manager_fk'),
        ('teachers', '0002_teacherevent_teacher_insert_insert_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='absenceresolution',
            name='absence_resolutions_status_check',
        ),
        migrations.AddConstraint(
            model_name='absenceresolution',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'makeup_scheduled', 'makeup_done', 'burned', 'waived'])), name='absence_resolutions_status_check'),
        ),
    ]
