# Generated by Django 5.2.15 on 2026-07-23 10:25

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_lessons', '0013_remove_absenceresolution_absence_resolutions_status_check_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='absenceresolution',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='absenceresolution',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='absenceresolution',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='absenceresolution',
            name='target_lesson_number',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='absenceresolutionevent',
            name='target_lesson_number',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='absenceresolution',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "extra_lessons_absenceresolutionevent" ("assigned_teacher_id", "created_at", "duration_minutes", "fact_lesson_id", "group_id", "id", "kind", "missed_lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "status", "student_id", "target_lesson_number") VALUES (NEW."assigned_teacher_id", NEW."created_at", NEW."duration_minutes", NEW."fact_lesson_id", NEW."group_id", NEW."id", NEW."kind", NEW."missed_lesson_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."scheduled_date", NEW."scheduled_time", NEW."status", NEW."student_id", NEW."target_lesson_number"); RETURN NULL;', hash='c0689d6a68f99ae79067f733d9ca80455fd9ba5f', operation='INSERT', pgid='pgtrigger_insert_insert_f67c0', table='absence_resolutions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='absenceresolution',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "extra_lessons_absenceresolutionevent" ("assigned_teacher_id", "created_at", "duration_minutes", "fact_lesson_id", "group_id", "id", "kind", "missed_lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "status", "student_id", "target_lesson_number") VALUES (NEW."assigned_teacher_id", NEW."created_at", NEW."duration_minutes", NEW."fact_lesson_id", NEW."group_id", NEW."id", NEW."kind", NEW."missed_lesson_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."scheduled_date", NEW."scheduled_time", NEW."status", NEW."student_id", NEW."target_lesson_number"); RETURN NULL;', hash='a6623fcb7b3f083ee4864dd64abf719787df4237', operation='UPDATE', pgid='pgtrigger_update_update_2b9ae', table='absence_resolutions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='absenceresolution',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "extra_lessons_absenceresolutionevent" ("assigned_teacher_id", "created_at", "duration_minutes", "fact_lesson_id", "group_id", "id", "kind", "missed_lesson_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "status", "student_id", "target_lesson_number") VALUES (OLD."assigned_teacher_id", OLD."created_at", OLD."duration_minutes", OLD."fact_lesson_id", OLD."group_id", OLD."id", OLD."kind", OLD."missed_lesson_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."scheduled_date", OLD."scheduled_time", OLD."status", OLD."student_id", OLD."target_lesson_number"); RETURN NULL;', hash='e31811a0a72a100bbb133c7c0fcd79ca22722c76', operation='DELETE', pgid='pgtrigger_delete_delete_6f9e4', table='absence_resolutions', when='AFTER')),
        ),
    ]
