# Generated by Django 5.1.4 on 2026-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('school_grade', models.IntegerField(blank=True, null=True)),
                ('platform_id', models.TextField(blank=True, null=True)),
                ('parent_name', models.TextField(blank=True, null=True)),
                ('first_purchase_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('pm', models.TextField(blank=True, null=True)),
                ('enrollment_status', models.TextField(default='enrolled')),
                ('frozen_until_month', models.IntegerField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_by', models.TextField(blank=True, null=True)),
                ('consent_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'students',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('school_grade__gte', 1), ('school_grade__lte', 11)), name='students_school_grade_check'), models.CheckConstraint(condition=models.Q(('enrollment_status__in', ['enrolled', 'not_enrolled', 'frozen', 'declined'])), name='students_enrollment_status_check'), models.CheckConstraint(condition=models.Q(('frozen_until_month__gte', 1), ('frozen_until_month__lte', 12)), name='students_frozen_until_month_check'), models.CheckConstraint(condition=models.Q(models.Q(('enrollment_status', 'frozen'), ('frozen_until_month__isnull', False)), models.Q(models.Q(('enrollment_status', 'frozen'), _negated=True), ('frozen_until_month__isnull', True)), _connector='OR'), name='students_check')],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE students ALTER COLUMN created_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE students ALTER COLUMN created_at DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE students ALTER COLUMN consent_given SET DEFAULT false;",
            reverse_sql="ALTER TABLE students ALTER COLUMN consent_given DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE students ALTER COLUMN enrollment_status SET DEFAULT 'enrolled';",
            reverse_sql="ALTER TABLE students ALTER COLUMN enrollment_status DROP DEFAULT;",
        ),
    ]
