# Generated by Django 5.2.15 on 2026-07-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='consent_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='consent_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='consent_given',
        ),
        migrations.RemoveField(
            model_name='student',
            name='consent_note',
        ),
    ]
