# Generated by Django 5.2.15 on 2026-07-06 08:00

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('students', '0002_remove_student_consent_at_remove_student_consent_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('full_name', models.TextField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('school_grade', models.IntegerField(blank=True, null=True)),
                ('platform_id', models.TextField(blank=True, null=True)),
                ('parent_name', models.TextField(blank=True, null=True)),
                ('first_purchase_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('pm', models.TextField(blank=True, null=True)),
                ('enrollment_status', models.TextField(default='enrolled')),
                ('frozen_until_month', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("age", "birth_date", "created_at", "enrollment_status", "first_purchase_date", "frozen_until_month", "full_name", "id", "parent_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "platform_id", "pm", "school_grade") VALUES (NEW."age", NEW."birth_date", NEW."created_at", NEW."enrollment_status", NEW."first_purchase_date", NEW."frozen_until_month", NEW."full_name", NEW."id", NEW."parent_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."platform_id", NEW."pm", NEW."school_grade"); RETURN NULL;', hash='8c786e1f335b8cb373f770bea083501eca6c8ce7', operation='INSERT', pgid='pgtrigger_insert_insert_95980', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "students_studentevent" ("age", "birth_date", "created_at", "enrollment_status", "first_purchase_date", "frozen_until_month", "full_name", "id", "parent_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "platform_id", "pm", "school_grade") VALUES (NEW."age", NEW."birth_date", NEW."created_at", NEW."enrollment_status", NEW."first_purchase_date", NEW."frozen_until_month", NEW."full_name", NEW."id", NEW."parent_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."platform_id", NEW."pm", NEW."school_grade"); RETURN NULL;', hash='2a8e2e197036eb76da20f97db42387c4d095470e', operation='UPDATE', pgid='pgtrigger_update_update_cfde9', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("age", "birth_date", "created_at", "enrollment_status", "first_purchase_date", "frozen_until_month", "full_name", "id", "parent_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "platform_id", "pm", "school_grade") VALUES (OLD."age", OLD."birth_date", OLD."created_at", OLD."enrollment_status", OLD."first_purchase_date", OLD."frozen_until_month", OLD."full_name", OLD."id", OLD."parent_name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone", OLD."platform_id", OLD."pm", OLD."school_grade"); RETURN NULL;', hash='f2a37513a194a62aaf764dfe825766ba6557cf6d', operation='DELETE', pgid='pgtrigger_delete_delete_30174', table='students', when='AFTER')),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='students.student'),
        ),
    ]
