# Generated by Django 5.2.15 on 2026-07-09 15:00

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentevent_student_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='student',
            name='bitrix24_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent1_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent1_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent1_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent2_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent2_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent2_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='bitrix24_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='parent1_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='parent1_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='parent1_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='parent2_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='parent2_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='parent2_phone',
            field=models.TextField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("age", "birth_date", "bitrix24_link", "created_at", "enrollment_status", "first_purchase_date", "frozen_until_month", "full_name", "id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "parent_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "platform_id", "pm", "school_grade") VALUES (NEW."age", NEW."birth_date", NEW."bitrix24_link", NEW."created_at", NEW."enrollment_status", NEW."first_purchase_date", NEW."frozen_until_month", NEW."full_name", NEW."id", NEW."parent1_email", NEW."parent1_name", NEW."parent1_phone", NEW."parent2_email", NEW."parent2_name", NEW."parent2_phone", NEW."parent_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."platform_id", NEW."pm", NEW."school_grade"); RETURN NULL;', hash='d547cd70f1392c42ef1f5bc6f7559e192260599c', operation='INSERT', pgid='pgtrigger_insert_insert_95980', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "students_studentevent" ("age", "birth_date", "bitrix24_link", "created_at", "enrollment_status", "first_purchase_date", "frozen_until_month", "full_name", "id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "parent_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "platform_id", "pm", "school_grade") VALUES (NEW."age", NEW."birth_date", NEW."bitrix24_link", NEW."created_at", NEW."enrollment_status", NEW."first_purchase_date", NEW."frozen_until_month", NEW."full_name", NEW."id", NEW."parent1_email", NEW."parent1_name", NEW."parent1_phone", NEW."parent2_email", NEW."parent2_name", NEW."parent2_phone", NEW."parent_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."platform_id", NEW."pm", NEW."school_grade"); RETURN NULL;', hash='369ff31e6a50417623b1313e2f8ffb2604e62f69', operation='UPDATE', pgid='pgtrigger_update_update_cfde9', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("age", "birth_date", "bitrix24_link", "created_at", "enrollment_status", "first_purchase_date", "frozen_until_month", "full_name", "id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "parent_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "platform_id", "pm", "school_grade") VALUES (OLD."age", OLD."birth_date", OLD."bitrix24_link", OLD."created_at", OLD."enrollment_status", OLD."first_purchase_date", OLD."frozen_until_month", OLD."full_name", OLD."id", OLD."parent1_email", OLD."parent1_name", OLD."parent1_phone", OLD."parent2_email", OLD."parent2_name", OLD."parent2_phone", OLD."parent_name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone", OLD."platform_id", OLD."pm", OLD."school_grade"); RETURN NULL;', hash='9051bfe9cdcd9abc1cedac5d993b92f0e0602386', operation='DELETE', pgid='pgtrigger_delete_delete_30174', table='students', when='AFTER')),
        ),
    ]
