# Generated by Django 5.2.15 on 2026-07-09 15:01
#
# Перенос legacy-контактов родителя в новую пару полей parent1_*.
# Старые колонки phone/parent_name удаляются следующей миграцией (0006).
#
# Raw SQL без пользовательского ввода (жёстко зашитые имена колонок, без
# интерполяции) — соответствует правилу CLAUDE.md о параметризованном SQL.

from django.db import migrations


def forward(apps, schema_editor):
    schema_editor.execute(
        "UPDATE students SET parent1_name = parent_name, parent1_phone = phone "
        "WHERE parent_name IS NOT NULL OR phone IS NOT NULL"
    )


def backward(apps, schema_editor):
    schema_editor.execute(
        "UPDATE students SET parent_name = parent1_name, phone = parent1_phone "
        "WHERE parent1_name IS NOT NULL OR parent1_phone IS NOT NULL"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_insert_insert_and_more'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
