# Generated by Django 5.2.15 on 2026-07-17 11:04

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentcomment'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='student',
            name='frozen_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='frozen_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='frozen_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='frozen_until',
            field=models.DateField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("age", "birth_date", "bitrix24_link", "created_at", "enrollment_status", "first_purchase_date", "frozen_from", "frozen_until", "frozen_until_month", "full_name", "id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id", "pm") VALUES (NEW."age", NEW."birth_date", NEW."bitrix24_link", NEW."created_at", NEW."enrollment_status", NEW."first_purchase_date", NEW."frozen_from", NEW."frozen_until", NEW."frozen_until_month", NEW."full_name", NEW."id", NEW."parent1_email", NEW."parent1_name", NEW."parent1_phone", NEW."parent2_email", NEW."parent2_name", NEW."parent2_phone", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."platform_id", NEW."pm"); RETURN NULL;', hash='f4f8d6ef3f9882e8a8546e86470040fb96588e30', operation='INSERT', pgid='pgtrigger_insert_insert_95980', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "students_studentevent" ("age", "birth_date", "bitrix24_link", "created_at", "enrollment_status", "first_purchase_date", "frozen_from", "frozen_until", "frozen_until_month", "full_name", "id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id", "pm") VALUES (NEW."age", NEW."birth_date", NEW."bitrix24_link", NEW."created_at", NEW."enrollment_status", NEW."first_purchase_date", NEW."frozen_from", NEW."frozen_until", NEW."frozen_until_month", NEW."full_name", NEW."id", NEW."parent1_email", NEW."parent1_name", NEW."parent1_phone", NEW."parent2_email", NEW."parent2_name", NEW."parent2_phone", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."platform_id", NEW."pm"); RETURN NULL;', hash='b1843d3f01148f1a25f8b9ed5fb84b160683abfa', operation='UPDATE', pgid='pgtrigger_update_update_cfde9', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("age", "birth_date", "bitrix24_link", "created_at", "enrollment_status", "first_purchase_date", "frozen_from", "frozen_until", "frozen_until_month", "full_name", "id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id", "pm") VALUES (OLD."age", OLD."birth_date", OLD."bitrix24_link", OLD."created_at", OLD."enrollment_status", OLD."first_purchase_date", OLD."frozen_from", OLD."frozen_until", OLD."frozen_until_month", OLD."full_name", OLD."id", OLD."parent1_email", OLD."parent1_name", OLD."parent1_phone", OLD."parent2_email", OLD."parent2_name", OLD."parent2_phone", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."platform_id", OLD."pm"); RETURN NULL;', hash='ffe97dc10479626366bb4314fef7084edb60e352', operation='DELETE', pgid='pgtrigger_delete_delete_30174', table='students', when='AFTER')),
        ),
    ]
