# Generated by Django 5.2.15 on 2026-07-17 11:29

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models
from django.db.models import F


def clamp_frozen_dates_forwards(apps, schema_editor):
    """Клампит frozen_from <= frozen_until у существующих строк ПЕРЕД добавлением
    CHECK-констрейнта students_frozen_dates_order_check (ниже в этой же миграции).

    Защита от резидуальных данных, попавших под баговую (до-клампную) версию
    0010_backfill_frozen_dates до её исправления в коде: Django НЕ перевыполняет
    уже применённую RunPython-миграцию при правке её тела, поэтому БД, где 0010
    отработала до фикса, могли сохранить неклампленные значения (frozen_from >
    frozen_until). Такая БД без этого шага упрётся в AddConstraint. Идемпотентно:
    на уже корректных данных .update() не затрагивает ни одной строки."""
    Student = apps.get_model('students', 'Student')
    Student.objects.filter(
        frozen_from__isnull=False,
        frozen_until__isnull=False,
        frozen_from__gt=F('frozen_until'),
    ).update(frozen_from=F('frozen_until'))


def clamp_frozen_dates_backwards(apps, schema_editor):
    """Необратимо: исходные (неклампленные) значения frozen_from не сохраняются.
    Безопасный no-op — откат не должен воссоздавать нарушение инварианта."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_backfill_frozen_dates'),
    ]

    operations = [
        migrations.RunPython(
            clamp_frozen_dates_forwards, clamp_frozen_dates_backwards
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='delete_delete',
        ),
        migrations.RemoveConstraint(
            model_name='student',
            name='students_frozen_until_month_check',
        ),
        migrations.RemoveConstraint(
            model_name='student',
            name='students_check',
        ),
        migrations.RemoveField(
            model_name='student',
            name='frozen_until_month',
        ),
        migrations.RemoveField(
            model_name='studentevent',
            name='frozen_until_month',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("age", "birth_date", "bitrix24_link", "created_at", "enrollment_status", "first_purchase_date", "frozen_from", "frozen_until", "full_name", "id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id", "pm") VALUES (NEW."age", NEW."birth_date", NEW."bitrix24_link", NEW."created_at", NEW."enrollment_status", NEW."first_purchase_date", NEW."frozen_from", NEW."frozen_until", NEW."full_name", NEW."id", NEW."parent1_email", NEW."parent1_name", NEW."parent1_phone", NEW."parent2_email", NEW."parent2_name", NEW."parent2_phone", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."platform_id", NEW."pm"); RETURN NULL;', hash='0a465ba5e758b7ed342fabc41da3f7664a2f0d01', operation='INSERT', pgid='pgtrigger_insert_insert_95980', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "students_studentevent" ("age", "birth_date", "bitrix24_link", "created_at", "enrollment_status", "first_purchase_date", "frozen_from", "frozen_until", "full_name", "id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id", "pm") VALUES (NEW."age", NEW."birth_date", NEW."bitrix24_link", NEW."created_at", NEW."enrollment_status", NEW."first_purchase_date", NEW."frozen_from", NEW."frozen_until", NEW."full_name", NEW."id", NEW."parent1_email", NEW."parent1_name", NEW."parent1_phone", NEW."parent2_email", NEW."parent2_name", NEW."parent2_phone", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."platform_id", NEW."pm"); RETURN NULL;', hash='eac0d59d6b1d2c3a19c34b7ff1af8ed2f7aa4ce2', operation='UPDATE', pgid='pgtrigger_update_update_cfde9', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("age", "birth_date", "bitrix24_link", "created_at", "enrollment_status", "first_purchase_date", "frozen_from", "frozen_until", "full_name", "id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id", "pm") VALUES (OLD."age", OLD."birth_date", OLD."bitrix24_link", OLD."created_at", OLD."enrollment_status", OLD."first_purchase_date", OLD."frozen_from", OLD."frozen_until", OLD."full_name", OLD."id", OLD."parent1_email", OLD."parent1_name", OLD."parent1_phone", OLD."parent2_email", OLD."parent2_name", OLD."parent2_phone", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."platform_id", OLD."pm"); RETURN NULL;', hash='93b36caac3be282c3737d34523fcea3b899e17a8', operation='DELETE', pgid='pgtrigger_delete_delete_30174', table='students', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('enrollment_status', 'frozen'), ('frozen_from__isnull', False), ('frozen_until__isnull', False)), models.Q(models.Q(('enrollment_status', 'frozen'), _negated=True), ('frozen_from__isnull', True), ('frozen_until__isnull', True)), _connector='OR'), name='students_frozen_dates_presence_check'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('frozen_from__isnull', True), ('frozen_until__gte', models.F('frozen_from')), _connector='OR'), name='students_frozen_dates_order_check'),
        ),
    ]
