# Generated by Django 5.2.15 on 2026-07-22 11:21

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_drop_frozen_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='studentevent',
            name='pm',
        ),
        migrations.AddField(
            model_name='student',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentevent',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("age", "birth_date", "bitrix24_link", "created_at", "enrollment_status", "first_purchase_date", "frozen_from", "frozen_until", "full_name", "id", "manager_id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id") VALUES (NEW."age", NEW."birth_date", NEW."bitrix24_link", NEW."created_at", NEW."enrollment_status", NEW."first_purchase_date", NEW."frozen_from", NEW."frozen_until", NEW."full_name", NEW."id", NEW."manager_id", NEW."parent1_email", NEW."parent1_name", NEW."parent1_phone", NEW."parent2_email", NEW."parent2_name", NEW."parent2_phone", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."platform_id"); RETURN NULL;', hash='b2877d9a0a6334fc9f5d8b58c29ce3081e56188c', operation='INSERT', pgid='pgtrigger_insert_insert_95980', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "students_studentevent" ("age", "birth_date", "bitrix24_link", "created_at", "enrollment_status", "first_purchase_date", "frozen_from", "frozen_until", "full_name", "id", "manager_id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id") VALUES (NEW."age", NEW."birth_date", NEW."bitrix24_link", NEW."created_at", NEW."enrollment_status", NEW."first_purchase_date", NEW."frozen_from", NEW."frozen_until", NEW."full_name", NEW."id", NEW."manager_id", NEW."parent1_email", NEW."parent1_name", NEW."parent1_phone", NEW."parent2_email", NEW."parent2_name", NEW."parent2_phone", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."platform_id"); RETURN NULL;', hash='32496235a53bee4992d7925f0d194db2578640fa', operation='UPDATE', pgid='pgtrigger_update_update_cfde9', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("age", "birth_date", "bitrix24_link", "created_at", "enrollment_status", "first_purchase_date", "frozen_from", "frozen_until", "full_name", "id", "manager_id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id") VALUES (OLD."age", OLD."birth_date", OLD."bitrix24_link", OLD."created_at", OLD."enrollment_status", OLD."first_purchase_date", OLD."frozen_from", OLD."frozen_until", OLD."full_name", OLD."id", OLD."manager_id", OLD."parent1_email", OLD."parent1_name", OLD."parent1_phone", OLD."parent2_email", OLD."parent2_name", OLD."parent2_phone", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."platform_id"); RETURN NULL;', hash='56002c51940a1129379a917febcc9feea4cadf5b', operation='DELETE', pgid='pgtrigger_delete_delete_30174', table='students', when='AFTER')),
        ),
    ]
