# Generated by Django 5.2.15 on 2026-07-24 08:11

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_student_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='studentevent',
            name='age',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("birth_date", "bitrix24_link", "created_at", "enrollment_status", "frozen_from", "frozen_until", "full_name", "id", "manager_id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id") VALUES (NEW."birth_date", NEW."bitrix24_link", NEW."created_at", NEW."enrollment_status", NEW."frozen_from", NEW."frozen_until", NEW."full_name", NEW."id", NEW."manager_id", NEW."parent1_email", NEW."parent1_name", NEW."parent1_phone", NEW."parent2_email", NEW."parent2_name", NEW."parent2_phone", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."platform_id"); RETURN NULL;', hash='28d83dfa577f1b5c7eb717cfb8e3442fa3f68567', operation='INSERT', pgid='pgtrigger_insert_insert_95980', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "students_studentevent" ("birth_date", "bitrix24_link", "created_at", "enrollment_status", "frozen_from", "frozen_until", "full_name", "id", "manager_id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id") VALUES (NEW."birth_date", NEW."bitrix24_link", NEW."created_at", NEW."enrollment_status", NEW."frozen_from", NEW."frozen_until", NEW."full_name", NEW."id", NEW."manager_id", NEW."parent1_email", NEW."parent1_name", NEW."parent1_phone", NEW."parent2_email", NEW."parent2_name", NEW."parent2_phone", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."platform_id"); RETURN NULL;', hash='548055e0e77fc641a774a95010630cc1c98adfa6', operation='UPDATE', pgid='pgtrigger_update_update_cfde9', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("birth_date", "bitrix24_link", "created_at", "enrollment_status", "frozen_from", "frozen_until", "full_name", "id", "manager_id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id") VALUES (OLD."birth_date", OLD."bitrix24_link", OLD."created_at", OLD."enrollment_status", OLD."frozen_from", OLD."frozen_until", OLD."full_name", OLD."id", OLD."manager_id", OLD."parent1_email", OLD."parent1_name", OLD."parent1_phone", OLD."parent2_email", OLD."parent2_name", OLD."parent2_phone", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."platform_id"); RETURN NULL;', hash='ffb44e109b40dafc1169e18bb2fce3c994e2fa27', operation='DELETE', pgid='pgtrigger_delete_delete_30174', table='students', when='AFTER')),
        ),
    ]
