# Generated by Django 5.2.15 on 2026-07-25 13:00

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    """Удаляет enrollment_status и даты заморозки из students (спека 2026-07-25).

    «Статусом» ученика стала стадия его последней сделки продления, а заморозка и
    уход — обычные переходы сделки без побочных эффектов. Снимаем три CHECK
    (домен статуса, связка frozen ↔ даты, порядок дат) и три колонки; заодно
    Django чистит те же колонки в теневой таблице pghistory (students_studentevent)
    и пересобирает триггеры под новый набор полей.
    """

    dependencies = [
        ('students', '0015_drop_not_enrolled_status'),
        # Бэкфил месяца заморозки читает students.frozen_until — он обязан
        # выполниться ДО удаления колонки (спека 2026-07-25).
        ('renewals', '0013_deal_frozen_until_month'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='student',
            name='delete_delete',
        ),
        migrations.RemoveConstraint(
            model_name='student',
            name='students_frozen_dates_presence_check',
        ),
        migrations.RemoveConstraint(
            model_name='student',
            name='students_frozen_dates_order_check',
        ),
        migrations.RemoveConstraint(
            model_name='student',
            name='students_enrollment_status_check',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='frozen_from',
        ),
        migrations.RemoveField(
            model_name='student',
            name='frozen_until',
        ),
        migrations.RemoveField(
            model_name='studentevent',
            name='enrollment_status',
        ),
        migrations.RemoveField(
            model_name='studentevent',
            name='frozen_from',
        ),
        migrations.RemoveField(
            model_name='studentevent',
            name='frozen_until',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("birth_date", "bitrix24_link", "created_at", "full_name", "id", "manager_id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id") VALUES (NEW."birth_date", NEW."bitrix24_link", NEW."created_at", NEW."full_name", NEW."id", NEW."manager_id", NEW."parent1_email", NEW."parent1_name", NEW."parent1_phone", NEW."parent2_email", NEW."parent2_name", NEW."parent2_phone", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."platform_id"); RETURN NULL;', hash='e811f3c44900ef777f75895f0e1c4716037c6fb7', operation='INSERT', pgid='pgtrigger_insert_insert_95980', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "students_studentevent" ("birth_date", "bitrix24_link", "created_at", "full_name", "id", "manager_id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id") VALUES (NEW."birth_date", NEW."bitrix24_link", NEW."created_at", NEW."full_name", NEW."id", NEW."manager_id", NEW."parent1_email", NEW."parent1_name", NEW."parent1_phone", NEW."parent2_email", NEW."parent2_name", NEW."parent2_phone", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."platform_id"); RETURN NULL;', hash='0bb7438cc28a6caf95752b7c3b54d609f619558e', operation='UPDATE', pgid='pgtrigger_update_update_cfde9', table='students', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='student',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "students_studentevent" ("birth_date", "bitrix24_link", "created_at", "full_name", "id", "manager_id", "parent1_email", "parent1_name", "parent1_phone", "parent2_email", "parent2_name", "parent2_phone", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_id") VALUES (OLD."birth_date", OLD."bitrix24_link", OLD."created_at", OLD."full_name", OLD."id", OLD."manager_id", OLD."parent1_email", OLD."parent1_name", OLD."parent1_phone", OLD."parent2_email", OLD."parent2_name", OLD."parent2_phone", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."platform_id"); RETURN NULL;', hash='1e057a00aa5ba94c1c1bfcc3b796f7f09b4039cd', operation='DELETE', pgid='pgtrigger_delete_delete_30174', table='students', when='AFTER')),
        ),
    ]
