# Generated by Django 5.1.4 on 2026-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserSettings',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('settings', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin_user_settings',
                'managed': True,
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE admin_user_settings ALTER COLUMN updated_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE admin_user_settings ALTER COLUMN updated_at DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE admin_user_settings ALTER COLUMN settings SET DEFAULT '{}'::jsonb;",
            reverse_sql="ALTER TABLE admin_user_settings ALTER COLUMN settings DROP DEFAULT;",
        ),
    ]
