# Generated by Django 5.2.15 on 2026-07-06 08:00

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserSettingsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('username', models.TextField(serialize=False)),
                ('settings', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='adminusersettings',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "settings_app_adminusersettingsevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "settings", "updated_at", "username") VALUES (_pgh_attach_context(), NOW(), \'insert\', NEW."username", NEW."settings", NEW."updated_at", NEW."username"); RETURN NULL;', hash='fb6a9d8e423da010b04a494cb815a017cc145ece', operation='INSERT', pgid='pgtrigger_insert_insert_141fd', table='admin_user_settings', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='adminusersettings',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "settings_app_adminusersettingsevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "settings", "updated_at", "username") VALUES (_pgh_attach_context(), NOW(), \'update\', NEW."username", NEW."settings", NEW."updated_at", NEW."username"); RETURN NULL;', hash='ad6df450456ef4ee530889964c5514343097c6f0', operation='UPDATE', pgid='pgtrigger_update_update_717cd', table='admin_user_settings', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='adminusersettings',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "settings_app_adminusersettingsevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "settings", "updated_at", "username") VALUES (_pgh_attach_context(), NOW(), \'delete\', OLD."username", OLD."settings", OLD."updated_at", OLD."username"); RETURN NULL;', hash='595db5215a8bca7aabb33fadc91e40b193d2c869', operation='DELETE', pgid='pgtrigger_delete_delete_71962', table='admin_user_settings', when='AFTER')),
        ),
        migrations.AddField(
            model_name='adminusersettingsevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='adminusersettingsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='settings_app.adminusersettings'),
        ),
    ]
