# Generated by Django 5.2.15 on 2026-07-03 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_lessonscheduleexception_and_more'),
        ('lessons', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedLesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('lesson_number', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.TextField(default='pending')),
                ('moved_from_date', models.DateField(blank=True, null=True)),
                ('moved_to_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('fact_lesson', models.ForeignKey(blank=True, db_column='fact_lesson_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_lesson', to='lessons.lesson', unique=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='planned_lessons', to='groups.group')),
                ('teacher', models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='planned_lessons', to='teachers.teacher')),
            ],
            options={
                'db_table': 'planned_lessons',
                'managed': True,
                'indexes': [models.Index(fields=['group', 'scheduled_date'], name='planned_lessons_group_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('seq__isnull', False)), fields=('group', 'seq'), name='planned_lessons_group_seq_key'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'overdue', 'done', 'cancelled', 'moved'])), name='planned_lessons_status_check'), models.CheckConstraint(condition=models.Q(models.Q(('lesson_number__isnull', True), ('seq__isnull', True)), models.Q(('lesson_number__isnull', False), ('seq__isnull', False)), _connector='OR'), name='planned_lessons_seq_number_together_check')],
            },
        ),
        # Django не ставит default на уровне БД для DateTimeField → raw-INSERT
        # плановых строк (apps/scheduling/repository.py, шаги 2/4) без явных
        # created_at/updated_at упал бы. Ставим DB-default now() (тот же приём,
        # что groups/0002 для lesson_schedule_exceptions.created_at).
        migrations.RunSQL(
            sql="ALTER TABLE planned_lessons ALTER COLUMN created_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE planned_lessons ALTER COLUMN created_at DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE planned_lessons ALTER COLUMN updated_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE planned_lessons ALTER COLUMN updated_at DROP DEFAULT;",
        ),
    ]
