# Generated by Django 5.2.15 on 2026-07-06 08:00

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupevent_groupscheduleslotevent_and_more'),
        ('lessons', '0002_lessonattendanceevent_lessonevent_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('scheduling', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedLessonEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('lesson_number', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.TextField(default='pending')),
                ('moved_from_date', models.DateField(blank=True, null=True)),
                ('moved_to_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plannedlesson',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "scheduling_plannedlessonevent" ("created_at", "fact_lesson_id", "group_id", "id", "lesson_number", "moved_from_date", "moved_to_date", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "seq", "status", "teacher_id", "updated_at") VALUES (NEW."created_at", NEW."fact_lesson_id", NEW."group_id", NEW."id", NEW."lesson_number", NEW."moved_from_date", NEW."moved_to_date", NEW."note", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."scheduled_date", NEW."scheduled_time", NEW."seq", NEW."status", NEW."teacher_id", NEW."updated_at"); RETURN NULL;', hash='8f8781a022646d6ead79bb05b8ff10e375045a6b', operation='INSERT', pgid='pgtrigger_insert_insert_303ec', table='planned_lessons', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plannedlesson',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "scheduling_plannedlessonevent" ("created_at", "fact_lesson_id", "group_id", "id", "lesson_number", "moved_from_date", "moved_to_date", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "seq", "status", "teacher_id", "updated_at") VALUES (NEW."created_at", NEW."fact_lesson_id", NEW."group_id", NEW."id", NEW."lesson_number", NEW."moved_from_date", NEW."moved_to_date", NEW."note", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."scheduled_date", NEW."scheduled_time", NEW."seq", NEW."status", NEW."teacher_id", NEW."updated_at"); RETURN NULL;', hash='b90f6953867577fb2faf6b92d36eeb003d7a6b59', operation='UPDATE', pgid='pgtrigger_update_update_09202', table='planned_lessons', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plannedlesson',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "scheduling_plannedlessonevent" ("created_at", "fact_lesson_id", "group_id", "id", "lesson_number", "moved_from_date", "moved_to_date", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "seq", "status", "teacher_id", "updated_at") VALUES (OLD."created_at", OLD."fact_lesson_id", OLD."group_id", OLD."id", OLD."lesson_number", OLD."moved_from_date", OLD."moved_to_date", OLD."note", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."scheduled_date", OLD."scheduled_time", OLD."seq", OLD."status", OLD."teacher_id", OLD."updated_at"); RETURN NULL;', hash='fa98921686557fb8836fe5c7f38178ddaf27fb5b', operation='DELETE', pgid='pgtrigger_delete_delete_049e3', table='planned_lessons', when='AFTER')),
        ),
        migrations.AddField(
            model_name='plannedlessonevent',
            name='fact_lesson',
            field=models.ForeignKey(blank=True, db_column='fact_lesson_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='plannedlessonevent',
            name='group',
            field=models.ForeignKey(db_column='group_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='groups.group'),
        ),
        migrations.AddField(
            model_name='plannedlessonevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='plannedlessonevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='scheduling.plannedlesson'),
        ),
        migrations.AddField(
            model_name='plannedlessonevent',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='teacher_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='teachers.teacher'),
        ),
    ]
