# Generated by Django 5.2.15 on 2026-07-19 07:46

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_plannedlessonevent_plannedlesson_insert_insert_and_more'),
        ('teachers', '0002_teacherevent_teacher_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='plannedlesson',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='plannedlesson',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='plannedlesson',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='plannedlesson',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, db_column='substitute_teacher_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='substitute_planned_lessons', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='plannedlessonevent',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, db_column='substitute_teacher_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='teachers.teacher'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plannedlesson',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "scheduling_plannedlessonevent" ("created_at", "fact_lesson_id", "group_id", "id", "lesson_number", "moved_from_date", "moved_to_date", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "seq", "status", "substitute_teacher_id", "teacher_id", "updated_at") VALUES (NEW."created_at", NEW."fact_lesson_id", NEW."group_id", NEW."id", NEW."lesson_number", NEW."moved_from_date", NEW."moved_to_date", NEW."note", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."scheduled_date", NEW."scheduled_time", NEW."seq", NEW."status", NEW."substitute_teacher_id", NEW."teacher_id", NEW."updated_at"); RETURN NULL;', hash='178c768fee8c0f14fdf44c3da14972b926c8d770', operation='INSERT', pgid='pgtrigger_insert_insert_303ec', table='planned_lessons', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plannedlesson',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "scheduling_plannedlessonevent" ("created_at", "fact_lesson_id", "group_id", "id", "lesson_number", "moved_from_date", "moved_to_date", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "seq", "status", "substitute_teacher_id", "teacher_id", "updated_at") VALUES (NEW."created_at", NEW."fact_lesson_id", NEW."group_id", NEW."id", NEW."lesson_number", NEW."moved_from_date", NEW."moved_to_date", NEW."note", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."scheduled_date", NEW."scheduled_time", NEW."seq", NEW."status", NEW."substitute_teacher_id", NEW."teacher_id", NEW."updated_at"); RETURN NULL;', hash='e6e68338d8aed137b2aa6a7c2a2879e0f9361333', operation='UPDATE', pgid='pgtrigger_update_update_09202', table='planned_lessons', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plannedlesson',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "scheduling_plannedlessonevent" ("created_at", "fact_lesson_id", "group_id", "id", "lesson_number", "moved_from_date", "moved_to_date", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "scheduled_date", "scheduled_time", "seq", "status", "substitute_teacher_id", "teacher_id", "updated_at") VALUES (OLD."created_at", OLD."fact_lesson_id", OLD."group_id", OLD."id", OLD."lesson_number", OLD."moved_from_date", OLD."moved_to_date", OLD."note", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."scheduled_date", OLD."scheduled_time", OLD."seq", OLD."status", OLD."substitute_teacher_id", OLD."teacher_id", OLD."updated_at"); RETURN NULL;', hash='dc80e686811e3191f57030c93a216fbd16168602', operation='DELETE', pgid='pgtrigger_delete_delete_049e3', table='planned_lessons', when='AFTER')),
        ),
    ]
