# Generated by Django 5.1.4 on 2026-06-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.TextField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tokens', to='teachers.teacher')),
            ],
            options={
                'db_table': 'tokens',
                'managed': True,
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE tokens ALTER COLUMN created_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE tokens ALTER COLUMN created_at DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE tokens ALTER COLUMN active SET DEFAULT true;",
            reverse_sql="ALTER TABLE tokens ALTER COLUMN active DROP DEFAULT;",
        ),
    ]
