# Generated by Django 5.1.4 on 2026-06-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lessons_done', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('remaining', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('sheet_row', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='groups.group')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='students.student')),
            ],
            options={
                'db_table': 'group_memberships',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('group', 'student'), name='group_memberships_group_id_student_id_key')],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE group_memberships ALTER COLUMN active SET DEFAULT true;",
            reverse_sql="ALTER TABLE group_memberships ALTER COLUMN active DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE group_memberships ALTER COLUMN lessons_done SET DEFAULT 0;",
            reverse_sql="ALTER TABLE group_memberships ALTER COLUMN lessons_done DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE group_memberships ALTER COLUMN remaining SET DEFAULT 0;",
            reverse_sql="ALTER TABLE group_memberships ALTER COLUMN remaining DROP DEFAULT;",
        ),
    ]
