# Generated by Django 5.2.15 on 2026-07-06 08:00

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupevent_groupscheduleslotevent_and_more'),
        ('memberships', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('students', '0002_remove_student_consent_at_remove_student_consent_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembershipEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('lessons_done', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('remaining', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('sheet_row', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupmembership',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "memberships_groupmembershipevent" ("active", "group_id", "id", "lessons_done", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "remaining", "sheet_row", "start_date", "student_id") VALUES (NEW."active", NEW."group_id", NEW."id", NEW."lessons_done", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."remaining", NEW."sheet_row", NEW."start_date", NEW."student_id"); RETURN NULL;', hash='1066fc70b8fa30c7c6ed0d01b356bbe4369834df', operation='INSERT', pgid='pgtrigger_insert_insert_41798', table='group_memberships', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupmembership',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "memberships_groupmembershipevent" ("active", "group_id", "id", "lessons_done", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "remaining", "sheet_row", "start_date", "student_id") VALUES (NEW."active", NEW."group_id", NEW."id", NEW."lessons_done", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."remaining", NEW."sheet_row", NEW."start_date", NEW."student_id"); RETURN NULL;', hash='73fb8936b25a10eb42a6e2459d920750066fd87b', operation='UPDATE', pgid='pgtrigger_update_update_f2722', table='group_memberships', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupmembership',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "memberships_groupmembershipevent" ("active", "group_id", "id", "lessons_done", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "remaining", "sheet_row", "start_date", "student_id") VALUES (OLD."active", OLD."group_id", OLD."id", OLD."lessons_done", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."remaining", OLD."sheet_row", OLD."start_date", OLD."student_id"); RETURN NULL;', hash='96e8d9290aaa7630b661fb2a6a30c34328195ad2', operation='DELETE', pgid='pgtrigger_delete_delete_c6e87', table='group_memberships', when='AFTER')),
        ),
        migrations.AddField(
            model_name='groupmembershipevent',
            name='group',
            field=models.ForeignKey(db_column='group_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupmembershipevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='groupmembershipevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='memberships.groupmembership'),
        ),
        migrations.AddField(
            model_name='groupmembershipevent',
            name='student',
            field=models.ForeignKey(db_column='student_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='students.student'),
        ),
    ]
