# Generated by Django 5.2.15 on 2026-07-10 08:51

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_groupmembershipevent_groupmembership_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='groupmembership',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='groupmembership',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='groupmembership',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='groupmembershipevent',
            name='remaining',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupmembership',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "memberships_groupmembershipevent" ("active", "group_id", "id", "lessons_done", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sheet_row", "start_date", "student_id") VALUES (NEW."active", NEW."group_id", NEW."id", NEW."lessons_done", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sheet_row", NEW."start_date", NEW."student_id"); RETURN NULL;', hash='a5726e188135798b1280bd648d3d52708dc3300a', operation='INSERT', pgid='pgtrigger_insert_insert_41798', table='group_memberships', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupmembership',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "memberships_groupmembershipevent" ("active", "group_id", "id", "lessons_done", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sheet_row", "start_date", "student_id") VALUES (NEW."active", NEW."group_id", NEW."id", NEW."lessons_done", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sheet_row", NEW."start_date", NEW."student_id"); RETURN NULL;', hash='b9fc7cc7ac57145f21dec3e9ab9b062ade31f0b7', operation='UPDATE', pgid='pgtrigger_update_update_f2722', table='group_memberships', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupmembership',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "memberships_groupmembershipevent" ("active", "group_id", "id", "lessons_done", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sheet_row", "start_date", "student_id") VALUES (OLD."active", OLD."group_id", OLD."id", OLD."lessons_done", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sheet_row", OLD."start_date", OLD."student_id"); RETURN NULL;', hash='75980313ec5aa6693abdaaeee9fca1af0ff6dd4a', operation='DELETE', pgid='pgtrigger_delete_delete_c6e87', table='group_memberships', when='AFTER')),
        ),
    ]
