# Generated by Django 5.2.15 on 2026-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupevent_groupscheduleslotevent_and_more'),
        ('memberships', '0003_remove_groupmembership_insert_insert_and_more'),
        ('students', '0008_studentcomment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['student'], name='gm_student_idx'),
        ),
    ]
