# Generated by Django 5.2.15 on 2026-07-13 16:22

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_gm_student_idx'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='groupmembership',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='groupmembership',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='groupmembership',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='transferred_from',
            field=models.ForeignKey(blank=True, db_column='transferred_from_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferred_to', to='memberships.groupmembership'),
        ),
        migrations.AddField(
            model_name='groupmembershipevent',
            name='transferred_from',
            field=models.ForeignKey(blank=True, db_column='transferred_from_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='memberships.groupmembership'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupmembership',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "memberships_groupmembershipevent" ("active", "group_id", "id", "lessons_done", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sheet_row", "start_date", "student_id", "transferred_from_id") VALUES (NEW."active", NEW."group_id", NEW."id", NEW."lessons_done", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sheet_row", NEW."start_date", NEW."student_id", NEW."transferred_from_id"); RETURN NULL;', hash='33da71466e2afa76f7d4a8647b1e2a68bd319444', operation='INSERT', pgid='pgtrigger_insert_insert_41798', table='group_memberships', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupmembership',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "memberships_groupmembershipevent" ("active", "group_id", "id", "lessons_done", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sheet_row", "start_date", "student_id", "transferred_from_id") VALUES (NEW."active", NEW."group_id", NEW."id", NEW."lessons_done", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sheet_row", NEW."start_date", NEW."student_id", NEW."transferred_from_id"); RETURN NULL;', hash='7aaa991f19ca660463c5d47358f8a8260882360d', operation='UPDATE', pgid='pgtrigger_update_update_f2722', table='group_memberships', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupmembership',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "memberships_groupmembershipevent" ("active", "group_id", "id", "lessons_done", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sheet_row", "start_date", "student_id", "transferred_from_id") VALUES (OLD."active", OLD."group_id", OLD."id", OLD."lessons_done", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sheet_row", OLD."start_date", OLD."student_id", OLD."transferred_from_id"); RETURN NULL;', hash='da679ad191bf7e53f9c6ad56f1c7053ee2d68b0d', operation='DELETE', pgid='pgtrigger_delete_delete_c6e87', table='group_memberships', when='AFTER')),
        ),
    ]
