# Generated by Django 5.1.4 on 2026-07-08 08:04

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directions', '0002_directionevent_direction_insert_insert_and_more'),
        ('payments', '0002_paymentevent_payment_insert_insert_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('students', '0003_studentevent_student_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalPipelineEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenewalStage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.TextField()),
                ('label', models.TextField()),
                ('color', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField()),
                ('kind', models.CharField(choices=[('progress', 'Прогресс'), ('decision', 'Решение'), ('won', 'Продлён'), ('lost', 'Ушёл')], max_length=10)),
                ('is_auto', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'renewal_stage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RenewalStageEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('key', models.TextField()),
                ('label', models.TextField()),
                ('color', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField()),
                ('kind', models.CharField(choices=[('progress', 'Прогресс'), ('decision', 'Решение'), ('won', 'Продлён'), ('lost', 'Ушёл')], max_length=10)),
                ('is_auto', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenewalActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('stage_change', 'Смена стадии'), ('comment', 'Комментарий'), ('payment_linked', 'Оплата'), ('system', 'Система')], max_length=16)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.payment')),
            ],
            options={
                'db_table': 'renewal_activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RenewalDeal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cycle_no', models.IntegerField()),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_touch_at', models.DateField(blank=True, null=True)),
                ('reason_code', models.TextField(blank=True, null=True)),
                ('stage_entered_at', models.DateTimeField(auto_now_add=True)),
                ('outcome_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, db_column='assignee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_deals', to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(db_column='direction_id', on_delete=django.db.models.deletion.RESTRICT, related_name='renewal_deals', to='directions.direction')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.RESTRICT, related_name='renewal_deals', to='students.student')),
            ],
            options={
                'db_table': 'renewal_deal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RenewalActivityEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('stage_change', 'Смена стадии'), ('comment', 'Комментарий'), ('payment_linked', 'Оплата'), ('system', 'Система')], max_length=16)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, db_column='author_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, db_column='payment_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.payment')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='renewals.renewalactivity')),
                ('deal', models.ForeignKey(db_column='deal_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='renewals.renewaldeal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='renewalactivity',
            name='deal',
            field=models.ForeignKey(db_column='deal_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='renewals.renewaldeal'),
        ),
        migrations.CreateModel(
            name='RenewalPipeline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'renewal_pipeline',
                'managed': True,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='renewal_pipeline_one_default')],
            },
        ),
        migrations.CreateModel(
            name='RenewalDealEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('cycle_no', models.IntegerField()),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_touch_at', models.DateField(blank=True, null=True)),
                ('reason_code', models.TextField(blank=True, null=True)),
                ('stage_entered_at', models.DateTimeField(auto_now_add=True)),
                ('outcome_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, db_column='assignee_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(db_column='direction_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='directions.direction')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='renewals.renewaldeal')),
                ('student', models.ForeignKey(db_column='student_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='students.student')),
                ('pipeline', models.ForeignKey(db_column='pipeline_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='renewals.renewalpipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='renewaldeal',
            name='pipeline',
            field=models.ForeignKey(db_column='pipeline_id', on_delete=django.db.models.deletion.RESTRICT, related_name='deals', to='renewals.renewalpipeline'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewalpipeline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewalpipelineevent" ("created_at", "id", "is_default", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."created_at", NEW."id", NEW."is_default", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='893f1ce928507b4daacbcbe0f46906c2d484be04', operation='INSERT', pgid='pgtrigger_insert_insert_11a09', table='renewal_pipeline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewalpipeline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "renewals_renewalpipelineevent" ("created_at", "id", "is_default", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."created_at", NEW."id", NEW."is_default", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='021c752a2ce93ff02f8ced191fbcbc070a2684c1', operation='UPDATE', pgid='pgtrigger_update_update_b1a19', table='renewal_pipeline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewalpipeline',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewalpipelineevent" ("created_at", "id", "is_default", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."created_at", OLD."id", OLD."is_default", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='a7b35295b3ea231d51bd03682d31fb11994f041b', operation='DELETE', pgid='pgtrigger_delete_delete_55c39', table='renewal_pipeline', when='AFTER')),
        ),
        migrations.AddField(
            model_name='renewalpipelineevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='renewalpipelineevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='renewals.renewalpipeline'),
        ),
        migrations.AddField(
            model_name='renewalstage',
            name='pipeline',
            field=models.ForeignKey(db_column='pipeline_id', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='renewals.renewalpipeline'),
        ),
        migrations.AddField(
            model_name='renewaldealevent',
            name='stage',
            field=models.ForeignKey(db_column='stage_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='renewals.renewalstage'),
        ),
        migrations.AddField(
            model_name='renewaldeal',
            name='stage',
            field=models.ForeignKey(db_column='stage_id', on_delete=django.db.models.deletion.RESTRICT, related_name='deals', to='renewals.renewalstage'),
        ),
        migrations.AddField(
            model_name='renewalactivityevent',
            name='from_stage',
            field=models.ForeignKey(blank=True, db_column='from_stage_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='renewals.renewalstage'),
        ),
        migrations.AddField(
            model_name='renewalactivityevent',
            name='to_stage',
            field=models.ForeignKey(blank=True, db_column='to_stage_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='renewals.renewalstage'),
        ),
        migrations.AddField(
            model_name='renewalactivity',
            name='from_stage',
            field=models.ForeignKey(blank=True, db_column='from_stage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='renewals.renewalstage'),
        ),
        migrations.AddField(
            model_name='renewalactivity',
            name='to_stage',
            field=models.ForeignKey(blank=True, db_column='to_stage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='renewals.renewalstage'),
        ),
        migrations.AddField(
            model_name='renewalstageevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='renewalstageevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='renewals.renewalstage'),
        ),
        migrations.AddField(
            model_name='renewalstageevent',
            name='pipeline',
            field=models.ForeignKey(db_column='pipeline_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='renewals.renewalpipeline'),
        ),
        migrations.AddIndex(
            model_name='renewalstage',
            index=models.Index(fields=['pipeline', 'sort_order'], name='renewal_stage_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='renewalstage',
            constraint=models.UniqueConstraint(fields=('pipeline', 'key'), name='renewal_stage_pipeline_key_uq'),
        ),
        migrations.AddConstraint(
            model_name='renewalstage',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['progress', 'decision', 'won', 'lost'])), name='renewal_stage_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='renewalstage',
            constraint=models.CheckConstraint(condition=models.Q(('color__isnull', True), ('color__regex', '^#[0-9a-fA-F]{6}$'), _connector='OR'), name='renewal_stage_color_check'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewalstage',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewalstageevent" ("color", "id", "is_auto", "key", "kind", "label", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "sort_order") VALUES (NEW."color", NEW."id", NEW."is_auto", NEW."key", NEW."kind", NEW."label", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pipeline_id", NEW."sort_order"); RETURN NULL;', hash='d4e22d18428cde5551c779cc819803d08ee15684', operation='INSERT', pgid='pgtrigger_insert_insert_c209a', table='renewal_stage', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewalstage',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "renewals_renewalstageevent" ("color", "id", "is_auto", "key", "kind", "label", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "sort_order") VALUES (NEW."color", NEW."id", NEW."is_auto", NEW."key", NEW."kind", NEW."label", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pipeline_id", NEW."sort_order"); RETURN NULL;', hash='5f64be785752f3397fc1de9772fa811354a476ff', operation='UPDATE', pgid='pgtrigger_update_update_0b298', table='renewal_stage', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewalstage',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewalstageevent" ("color", "id", "is_auto", "key", "kind", "label", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "sort_order") VALUES (OLD."color", OLD."id", OLD."is_auto", OLD."key", OLD."kind", OLD."label", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pipeline_id", OLD."sort_order"); RETURN NULL;', hash='59152721bb43f6a0fbbe8fdf214cabae148834c9', operation='DELETE', pgid='pgtrigger_delete_delete_5d810', table='renewal_stage', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='renewaldeal',
            index=models.Index(condition=models.Q(('outcome_at__isnull', True)), fields=['stage'], name='renewal_deal_open_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='renewaldeal',
            index=models.Index(fields=['assignee'], name='renewal_deal_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='renewaldeal',
            index=models.Index(fields=['student'], name='renewal_deal_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='renewaldeal',
            constraint=models.UniqueConstraint(fields=('student', 'direction', 'cycle_no'), name='renewal_deal_cycle_uq'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "direction_id", "expected_amount", "id", "next_touch_at", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (NEW."assignee_id", NEW."created_at", NEW."cycle_no", NEW."direction_id", NEW."expected_amount", NEW."id", NEW."next_touch_at", NEW."outcome_at", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pipeline_id", NEW."reason_code", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='3059b496d16197b37988515613b0470a780c144c', operation='INSERT', pgid='pgtrigger_insert_insert_6053f', table='renewal_deal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "direction_id", "expected_amount", "id", "next_touch_at", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (NEW."assignee_id", NEW."created_at", NEW."cycle_no", NEW."direction_id", NEW."expected_amount", NEW."id", NEW."next_touch_at", NEW."outcome_at", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pipeline_id", NEW."reason_code", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='8dad454ffe81ae8b20907d4a3a77dccb7da7f28d', operation='UPDATE', pgid='pgtrigger_update_update_f53f2', table='renewal_deal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "direction_id", "expected_amount", "id", "next_touch_at", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (OLD."assignee_id", OLD."created_at", OLD."cycle_no", OLD."direction_id", OLD."expected_amount", OLD."id", OLD."next_touch_at", OLD."outcome_at", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pipeline_id", OLD."reason_code", OLD."stage_entered_at", OLD."stage_id", OLD."student_id", OLD."updated_at"); RETURN NULL;', hash='4cfdf26cf4d87734ef5b78d2d356623bb5129b3e', operation='DELETE', pgid='pgtrigger_delete_delete_66911', table='renewal_deal', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='renewalactivity',
            index=models.Index(fields=['deal', '-created_at'], name='renewal_activity_deal_idx'),
        ),
        migrations.AddConstraint(
            model_name='renewalactivity',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['stage_change', 'comment', 'payment_linked', 'system'])), name='renewal_activity_kind_check'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewalactivity',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewalactivityevent" ("author_id", "body", "created_at", "deal_id", "from_stage_id", "id", "kind", "payment_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "to_stage_id") VALUES (NEW."author_id", NEW."body", NEW."created_at", NEW."deal_id", NEW."from_stage_id", NEW."id", NEW."kind", NEW."payment_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."to_stage_id"); RETURN NULL;', hash='7467746bb2a018d01a6ed353aa2a992920efbd45', operation='INSERT', pgid='pgtrigger_insert_insert_dc831', table='renewal_activity', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewalactivity',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewalactivityevent" ("author_id", "body", "created_at", "deal_id", "from_stage_id", "id", "kind", "payment_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "to_stage_id") VALUES (OLD."author_id", OLD."body", OLD."created_at", OLD."deal_id", OLD."from_stage_id", OLD."id", OLD."kind", OLD."payment_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."to_stage_id"); RETURN NULL;', hash='c62cf6d13aa3cd4ae3b3a9aae79578a49bbecadd', operation='DELETE', pgid='pgtrigger_delete_delete_e213a', table='renewal_activity', when='AFTER')),
        ),
    ]
