# Generated by Django 5.2.15 on 2026-07-12 15:26

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0003_split_lesson_progress_stage'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='renewaldeal',
            name='due_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renewaldealevent',
            name='due_at',
            field=models.DateField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "direction_id", "due_at", "expected_amount", "id", "next_touch_at", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (NEW."assignee_id", NEW."created_at", NEW."cycle_no", NEW."direction_id", NEW."due_at", NEW."expected_amount", NEW."id", NEW."next_touch_at", NEW."outcome_at", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pipeline_id", NEW."reason_code", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='045fc4ff792b4b7802612b6411b34bee457936e9', operation='INSERT', pgid='pgtrigger_insert_insert_6053f', table='renewal_deal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "direction_id", "due_at", "expected_amount", "id", "next_touch_at", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (NEW."assignee_id", NEW."created_at", NEW."cycle_no", NEW."direction_id", NEW."due_at", NEW."expected_amount", NEW."id", NEW."next_touch_at", NEW."outcome_at", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pipeline_id", NEW."reason_code", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='5ac19efd36fc85e08759201997e3dfbc361f3ba4', operation='UPDATE', pgid='pgtrigger_update_update_f53f2', table='renewal_deal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "direction_id", "due_at", "expected_amount", "id", "next_touch_at", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (OLD."assignee_id", OLD."created_at", OLD."cycle_no", OLD."direction_id", OLD."due_at", OLD."expected_amount", OLD."id", OLD."next_touch_at", OLD."outcome_at", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pipeline_id", OLD."reason_code", OLD."stage_entered_at", OLD."stage_id", OLD."student_id", OLD."updated_at"); RETURN NULL;', hash='aacca0d456d7119f8d2f431510911b3a8c1ee54a', operation='DELETE', pgid='pgtrigger_delete_delete_66911', table='renewal_deal', when='AFTER')),
        ),
    ]
