# Generated by Django 5.2.15 on 2026-07-12 16:35

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0006_wipe_deals_for_student_model'),
        ('students', '0008_studentcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='delete_delete',
        ),
        migrations.RemoveConstraint(
            model_name='renewaldeal',
            name='renewal_deal_cycle_uq',
        ),
        migrations.RemoveField(
            model_name='renewaldeal',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='renewaldealevent',
            name='direction',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "due_at", "expected_amount", "id", "next_touch_at", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (NEW."assignee_id", NEW."created_at", NEW."cycle_no", NEW."due_at", NEW."expected_amount", NEW."id", NEW."next_touch_at", NEW."outcome_at", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pipeline_id", NEW."reason_code", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='466d73186e3e3c3f717cdc670039b2f6cb576947', operation='INSERT', pgid='pgtrigger_insert_insert_6053f', table='renewal_deal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "due_at", "expected_amount", "id", "next_touch_at", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (NEW."assignee_id", NEW."created_at", NEW."cycle_no", NEW."due_at", NEW."expected_amount", NEW."id", NEW."next_touch_at", NEW."outcome_at", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pipeline_id", NEW."reason_code", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='af8442b0a0b1254c4309572ea0f083faf8d7f795', operation='UPDATE', pgid='pgtrigger_update_update_f53f2', table='renewal_deal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "due_at", "expected_amount", "id", "next_touch_at", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (OLD."assignee_id", OLD."created_at", OLD."cycle_no", OLD."due_at", OLD."expected_amount", OLD."id", OLD."next_touch_at", OLD."outcome_at", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pipeline_id", OLD."reason_code", OLD."stage_entered_at", OLD."stage_id", OLD."student_id", OLD."updated_at"); RETURN NULL;', hash='170e42042f66feb3540b1f0fe488fe4c7491edcb', operation='DELETE', pgid='pgtrigger_delete_delete_66911', table='renewal_deal', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='renewaldeal',
            constraint=models.UniqueConstraint(fields=('student', 'cycle_no'), name='renewal_deal_student_cycle_uq'),
        ),
    ]
