# Generated by Django 5.2.15 on 2026-07-19 21:35

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0010_frozen_autostage'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='renewaldeal',
            name='next_touch_at',
        ),
        migrations.RemoveField(
            model_name='renewaldealevent',
            name='next_touch_at',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "due_at", "id", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (NEW."assignee_id", NEW."created_at", NEW."cycle_no", NEW."due_at", NEW."id", NEW."outcome_at", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pipeline_id", NEW."reason_code", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='fd4ab386c95c3732c9d6cc5a10149fdad0153995', operation='INSERT', pgid='pgtrigger_insert_insert_6053f', table='renewal_deal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "due_at", "id", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (NEW."assignee_id", NEW."created_at", NEW."cycle_no", NEW."due_at", NEW."id", NEW."outcome_at", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pipeline_id", NEW."reason_code", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='2be3f652cc70e7289360540c06cba6a18ea35ec7', operation='UPDATE', pgid='pgtrigger_update_update_f53f2', table='renewal_deal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "due_at", "id", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (OLD."assignee_id", OLD."created_at", OLD."cycle_no", OLD."due_at", OLD."id", OLD."outcome_at", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pipeline_id", OLD."reason_code", OLD."stage_entered_at", OLD."stage_id", OLD."student_id", OLD."updated_at"); RETURN NULL;', hash='b85d66549647cf791ac305f937183fa51707a83b', operation='DELETE', pgid='pgtrigger_delete_delete_66911', table='renewal_deal', when='AFTER')),
        ),
    ]
