# Generated by Django 5.2.15 on 2026-07-25 11:13

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0013_deal_frozen_until_month'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='renewaldealevent',
            name='frozen_until_month',
            field=models.DateField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "due_at", "frozen_until_month", "id", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (NEW."assignee_id", NEW."created_at", NEW."cycle_no", NEW."due_at", NEW."frozen_until_month", NEW."id", NEW."outcome_at", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pipeline_id", NEW."reason_code", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='6b78378090472f18d762aea9ab7fa0afbf4fd06d', operation='INSERT', pgid='pgtrigger_insert_insert_6053f', table='renewal_deal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "due_at", "frozen_until_month", "id", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (NEW."assignee_id", NEW."created_at", NEW."cycle_no", NEW."due_at", NEW."frozen_until_month", NEW."id", NEW."outcome_at", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pipeline_id", NEW."reason_code", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='ce11841610fb0164257b0b3142e02ddc62c32563', operation='UPDATE', pgid='pgtrigger_update_update_f53f2', table='renewal_deal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "due_at", "frozen_until_month", "id", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (OLD."assignee_id", OLD."created_at", OLD."cycle_no", OLD."due_at", OLD."frozen_until_month", OLD."id", OLD."outcome_at", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pipeline_id", OLD."reason_code", OLD."stage_entered_at", OLD."stage_id", OLD."student_id", OLD."updated_at"); RETURN NULL;', hash='6a17bd060da23d1d58ce43da2db457549534f592', operation='DELETE', pgid='pgtrigger_delete_delete_66911', table='renewal_deal', when='AFTER')),
        ),
    ]
