# Generated by Django 5.2.15 on 2026-08-06 09:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewals', '0016_stage_allow_mid_cycle'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='renewaldeal',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='renewaldeal',
            name='directions_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renewaldealevent',
            name='directions_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "directions_snapshot", "due_at", "frozen_until_month", "id", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (NEW."assignee_id", NEW."created_at", NEW."cycle_no", NEW."directions_snapshot", NEW."due_at", NEW."frozen_until_month", NEW."id", NEW."outcome_at", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pipeline_id", NEW."reason_code", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='a38f12cbece8ba4a4c7366b1b85a21f2c112a8ec', operation='INSERT', pgid='pgtrigger_insert_insert_6053f', table='renewal_deal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "directions_snapshot", "due_at", "frozen_until_month", "id", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (NEW."assignee_id", NEW."created_at", NEW."cycle_no", NEW."directions_snapshot", NEW."due_at", NEW."frozen_until_month", NEW."id", NEW."outcome_at", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pipeline_id", NEW."reason_code", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='538263d08ecea157b59b766a439560c337b8637b', operation='UPDATE', pgid='pgtrigger_update_update_f53f2', table='renewal_deal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='renewaldeal',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "renewals_renewaldealevent" ("assignee_id", "created_at", "cycle_no", "directions_snapshot", "due_at", "frozen_until_month", "id", "outcome_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pipeline_id", "reason_code", "stage_entered_at", "stage_id", "student_id", "updated_at") VALUES (OLD."assignee_id", OLD."created_at", OLD."cycle_no", OLD."directions_snapshot", OLD."due_at", OLD."frozen_until_month", OLD."id", OLD."outcome_at", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pipeline_id", OLD."reason_code", OLD."stage_entered_at", OLD."stage_id", OLD."student_id", OLD."updated_at"); RETURN NULL;', hash='9c87b1f7125a862a2cfea33279b34509fd4f4608', operation='DELETE', pgid='pgtrigger_delete_delete_66911', table='renewal_deal', when='AFTER')),
        ),
    ]
