# Generated by Django 5.2.15 on 2026-08-03 16:05

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('teachers', '0002_teacherevent_teacher_insert_insert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRecipient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_recipient', to='teachers.teacher')),
            ],
            options={
                'db_table': 'telegram_recipients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('full_name', models.TextField()),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telegram_users',
                'managed': True,
                'indexes': [models.Index(fields=['username'], name='telegram_users_username_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramRecipientEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='notifications.telegramrecipient')),
                ('teacher', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='teachers.teacher')),
                ('telegram_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='notifications.telegramuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='telegramrecipient',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='notifications.telegramuser'),
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('channel', models.TextField()),
                ('chat_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('dedup_key', models.TextField(unique=True)),
                ('source_kind', models.TextField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(default='queued')),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_messages', to='teachers.teacher')),
            ],
            options={
                'db_table': 'notification_messages',
                'managed': True,
                'indexes': [models.Index(condition=models.Q(('status', 'queued')), fields=['created_at'], name='notif_queued_idx'), models.Index(fields=['kind', '-created_at'], name='notif_kind_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['morning_digest', 'fill_digest', 'makeup_assigned', 'makeup_changed', 'makeup_cancelled', 'lesson_moved', 'lesson_cancelled', 'substitute_assigned', 'substitute_removed'])), name='notification_messages_kind_check'), models.CheckConstraint(condition=models.Q(('channel__in', ['dm', 'group_chat'])), name='notification_messages_channel_check'), models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'sent', 'failed'])), name='notification_messages_status_check')],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='telegramrecipient',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notifications_telegramrecipientevent" ("blocked_reason", "created_at", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "teacher_id", "telegram_user_id", "updated_at") VALUES (NEW."blocked_reason", NEW."created_at", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."teacher_id", NEW."telegram_user_id", NEW."updated_at"); RETURN NULL;', hash='dde9d31ab33f25ec30df466f506643a8263137eb', operation='INSERT', pgid='pgtrigger_insert_insert_33b05', table='telegram_recipients', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='telegramrecipient',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "notifications_telegramrecipientevent" ("blocked_reason", "created_at", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "teacher_id", "telegram_user_id", "updated_at") VALUES (NEW."blocked_reason", NEW."created_at", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."teacher_id", NEW."telegram_user_id", NEW."updated_at"); RETURN NULL;', hash='b50d27ef5e6f3abf2ae66e4925d4b6a080a8a62a', operation='UPDATE', pgid='pgtrigger_update_update_0eae7', table='telegram_recipients', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='telegramrecipient',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notifications_telegramrecipientevent" ("blocked_reason", "created_at", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "teacher_id", "telegram_user_id", "updated_at") VALUES (OLD."blocked_reason", OLD."created_at", OLD."id", OLD."is_active", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."teacher_id", OLD."telegram_user_id", OLD."updated_at"); RETURN NULL;', hash='824945a0f469af5a5a68c19db6da7a0051cd4449', operation='DELETE', pgid='pgtrigger_delete_delete_789bc', table='telegram_recipients', when='AFTER')),
        ),
    ]
