# Generated by Django 5.2.15 on 2026-08-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('teachers', '0002_teacherevent_teacher_insert_insert_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='telegramrecipient',
            constraint=models.UniqueConstraint(fields=('telegram_user',), name='telegram_recipients_user_key'),
        ),
    ]
