# Generated by Django 5.2.15 on 2026-08-05 08:53

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_telegramrecipient_telegram_recipients_user_key'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotificationSettingsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='notificationsettings',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notifications_notificationsettingsevent" ("id", "is_enabled", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by") VALUES (NEW."id", NEW."is_enabled", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."updated_by"); RETURN NULL;', hash='f49f9ef7f08789d20d5917b0bebb191ac8818d56', operation='INSERT', pgid='pgtrigger_insert_insert_b3010', table='notification_settings', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='notificationsettings',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "notifications_notificationsettingsevent" ("id", "is_enabled", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by") VALUES (NEW."id", NEW."is_enabled", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."updated_by"); RETURN NULL;', hash='4da7c81756a55d90646df47b74949575e8c33fa5', operation='UPDATE', pgid='pgtrigger_update_update_b5bf4', table='notification_settings', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='notificationsettings',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notifications_notificationsettingsevent" ("id", "is_enabled", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "updated_by") VALUES (OLD."id", OLD."is_enabled", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated_at", OLD."updated_by"); RETURN NULL;', hash='cca6325dc7eddc23eac67b7fa3fddb45df9220e6', operation='DELETE', pgid='pgtrigger_delete_delete_29b82', table='notification_settings', when='AFTER')),
        ),
        migrations.AddField(
            model_name='notificationsettingsevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='notificationsettingsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='notifications.notificationsettings'),
        ),
    ]
