# Generated by Django 5.1.4 on 2026-06-11 13:46

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directions', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscriptions_count', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.TextField(blank=True, null=True)),
                ('direction', models.ForeignKey(blank=True, db_column='direction_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='directions.direction')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='students.student')),
            ],
            options={
                'db_table': 'payments',
                'managed': True,
                'indexes': [models.Index(fields=['student'], name='payments_student_idx'), models.Index(fields=['direction'], name='payments_direction_idx'), models.Index(fields=['paid_at'], name='payments_paid_at_idx'), models.Index(fields=['-paid_at', '-id'], name='payments_paid_at_desc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subscriptions_count__gt', 0)), name='payments_subscriptions_count_check'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='payments_unit_price_check'), models.CheckConstraint(condition=models.Q(models.Q(('direction__isnull', True), ('subscriptions_count__isnull', True)), models.Q(('direction__isnull', False), ('subscriptions_count__isnull', False), ('subscriptions_count__gt', 0)), _connector='OR'), name='payments_direction_count_match'), models.CheckConstraint(condition=models.Q(('subscriptions_count__isnull', True), ('total_amount', django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('subscriptions_count'))), _connector='OR'), name='payments_total_match')],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE payments ALTER COLUMN created_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE payments ALTER COLUMN created_at DROP DEFAULT;",
        ),
    ]
