# Generated by Django 5.2.15 on 2026-07-06 08:00

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_directionevent_direction_insert_insert_and_more'),
        ('payments', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('students', '0002_remove_student_consent_at_remove_student_consent_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('subscriptions_count', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_paymentevent" ("created_at", "created_by", "direction_id", "id", "note", "paid_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id", "subscriptions_count", "total_amount", "unit_price") VALUES (NEW."created_at", NEW."created_by", NEW."direction_id", NEW."id", NEW."note", NEW."paid_at", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."student_id", NEW."subscriptions_count", NEW."total_amount", NEW."unit_price"); RETURN NULL;', hash='93981bffcaf31f335880db4fce7a41903601362f', operation='INSERT', pgid='pgtrigger_insert_insert_24a65', table='payments', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payments_paymentevent" ("created_at", "created_by", "direction_id", "id", "note", "paid_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id", "subscriptions_count", "total_amount", "unit_price") VALUES (NEW."created_at", NEW."created_by", NEW."direction_id", NEW."id", NEW."note", NEW."paid_at", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."student_id", NEW."subscriptions_count", NEW."total_amount", NEW."unit_price"); RETURN NULL;', hash='c8ec5576dc1cd8158d964b09b3e2d7e498a7730f', operation='UPDATE', pgid='pgtrigger_update_update_dd546', table='payments', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_paymentevent" ("created_at", "created_by", "direction_id", "id", "note", "paid_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id", "subscriptions_count", "total_amount", "unit_price") VALUES (OLD."created_at", OLD."created_by", OLD."direction_id", OLD."id", OLD."note", OLD."paid_at", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."student_id", OLD."subscriptions_count", OLD."total_amount", OLD."unit_price"); RETURN NULL;', hash='1ee3dc951f76517a06f79fb0065987820887d4df', operation='DELETE', pgid='pgtrigger_delete_delete_b2c62', table='payments', when='AFTER')),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='direction',
            field=models.ForeignKey(blank=True, db_column='direction_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='directions.direction'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='student',
            field=models.ForeignKey(db_column='student_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='students.student'),
        ),
    ]
