# Generated by Django 5.2.15 on 2026-07-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentevent_payment_insert_insert_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_direction_count_match',
        ),
    ]
