# Generated by Django 5.2.15 on 2026-07-10 18:58

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_remove_direction_insert_insert_and_more'),
        ('payments', '0004_backfill_legacy_subscriptions_count'),
        ('students', '0008_studentcomment'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='payment',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payment',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payment',
            name='delete_delete',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_subscriptions_count_check',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_total_match',
        ),
        migrations.AddField(
            model_name='payment',
            name='kind',
            field=models.TextField(db_default='purchase', default='purchase'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lessons_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='kind',
            field=models.TextField(db_default='purchase', default='purchase'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='lessons_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_paymentevent" ("created_at", "created_by", "direction_id", "id", "kind", "lessons_count", "note", "paid_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id", "subscriptions_count", "total_amount", "unit_price") VALUES (NEW."created_at", NEW."created_by", NEW."direction_id", NEW."id", NEW."kind", NEW."lessons_count", NEW."note", NEW."paid_at", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."student_id", NEW."subscriptions_count", NEW."total_amount", NEW."unit_price"); RETURN NULL;', hash='20ccc8d71f653c7461f9b64ef23c084051912723', operation='INSERT', pgid='pgtrigger_insert_insert_24a65', table='payments', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payments_paymentevent" ("created_at", "created_by", "direction_id", "id", "kind", "lessons_count", "note", "paid_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id", "subscriptions_count", "total_amount", "unit_price") VALUES (NEW."created_at", NEW."created_by", NEW."direction_id", NEW."id", NEW."kind", NEW."lessons_count", NEW."note", NEW."paid_at", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."student_id", NEW."subscriptions_count", NEW."total_amount", NEW."unit_price"); RETURN NULL;', hash='429dc994a2f136345c53c6e457a0ab563c9e7f36', operation='UPDATE', pgid='pgtrigger_update_update_dd546', table='payments', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_paymentevent" ("created_at", "created_by", "direction_id", "id", "kind", "lessons_count", "note", "paid_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id", "subscriptions_count", "total_amount", "unit_price") VALUES (OLD."created_at", OLD."created_by", OLD."direction_id", OLD."id", OLD."kind", OLD."lessons_count", OLD."note", OLD."paid_at", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."student_id", OLD."subscriptions_count", OLD."total_amount", OLD."unit_price"); RETURN NULL;', hash='eb84d2c5abd451c3417c27a3396b546f1fa0a092', operation='DELETE', pgid='pgtrigger_delete_delete_b2c62', table='payments', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['purchase', 'refund'])), name='payments_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'purchase'), _negated=True), models.Q(('lessons_count__gt', 0), ('total_amount__gte', 0)), _connector='OR'), name='payments_purchase_signs'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'refund'), _negated=True), models.Q(('lessons_count__lt', 0), ('total_amount__lte', 0)), _connector='OR'), name='payments_refund_signs'),
        ),
    ]
