# Generated by Django 5.2.15 on 2026-07-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_backfill_lessons_count_and_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='lessons_count',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='lessons_count',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
    ]
