# Generated by Django 5.2.15 on 2026-07-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_remove_direction_insert_insert_and_more'),
        ('payments', '0007_lessons_count_decimal'),
        ('students', '0011_drop_frozen_month'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_purchase_signs',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_refund_signs',
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'purchase'), _negated=True), models.Q(('lessons_count__isnull', False), ('lessons_count__gt', 0), ('total_amount__gte', 0)), _connector='OR'), name='payments_purchase_signs'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'refund'), _negated=True), models.Q(('lessons_count__isnull', False), ('lessons_count__lt', 0), ('total_amount__lte', 0)), _connector='OR'), name='payments_refund_signs'),
        ),
    ]
