# Generated by Django 5.2.15 on 2026-07-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_remove_direction_insert_insert_and_more'),
        ('payments', '0008_remove_payment_payments_purchase_signs_and_more'),
        ('students', '0012_student_manager_fk'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_kind_check',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_purchase_signs',
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['purchase', 'refund', 'extra'])), name='payments_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['purchase', 'extra']), _negated=True), models.Q(('lessons_count__isnull', False), ('lessons_count__gt', 0), ('total_amount__gte', 0)), _connector='OR'), name='payments_purchase_signs'),
        ),
    ]
