# Generated by Django 5.2.15 on 2026-07-28 14:29

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0004_remove_direction_insert_insert_and_more'),
        ('payments', '0009_remove_payment_payments_kind_check_and_more'),
        ('students', '0016_drop_enrollment_status'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='payment',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payment',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='payment',
            name='delete_delete',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_kind_check',
        ),
        migrations.AddField(
            model_name='payment',
            name='parent_payment',
            field=models.ForeignKey(blank=True, db_column='parent_payment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='parent_payment',
            field=models.ForeignKey(blank=True, db_column='parent_payment_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='subscription_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_paymentevent" ("created_at", "created_by", "direction_id", "id", "kind", "lessons_count", "note", "paid_at", "parent_payment_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id", "subscription_index", "subscriptions_count", "total_amount", "unit_price") VALUES (NEW."created_at", NEW."created_by", NEW."direction_id", NEW."id", NEW."kind", NEW."lessons_count", NEW."note", NEW."paid_at", NEW."parent_payment_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."student_id", NEW."subscription_index", NEW."subscriptions_count", NEW."total_amount", NEW."unit_price"); RETURN NULL;', hash='cbb3afadd7804ddbb704c8ae875e8fa643f1d526', operation='INSERT', pgid='pgtrigger_insert_insert_24a65', table='payments', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "payments_paymentevent" ("created_at", "created_by", "direction_id", "id", "kind", "lessons_count", "note", "paid_at", "parent_payment_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id", "subscription_index", "subscriptions_count", "total_amount", "unit_price") VALUES (NEW."created_at", NEW."created_by", NEW."direction_id", NEW."id", NEW."kind", NEW."lessons_count", NEW."note", NEW."paid_at", NEW."parent_payment_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."student_id", NEW."subscription_index", NEW."subscriptions_count", NEW."total_amount", NEW."unit_price"); RETURN NULL;', hash='3387367249033f469e2628b2c5381af722e5407f', operation='UPDATE', pgid='pgtrigger_update_update_dd546', table='payments', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='payment',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "payments_paymentevent" ("created_at", "created_by", "direction_id", "id", "kind", "lessons_count", "note", "paid_at", "parent_payment_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "student_id", "subscription_index", "subscriptions_count", "total_amount", "unit_price") VALUES (OLD."created_at", OLD."created_by", OLD."direction_id", OLD."id", OLD."kind", OLD."lessons_count", OLD."note", OLD."paid_at", OLD."parent_payment_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."student_id", OLD."subscription_index", OLD."subscriptions_count", OLD."total_amount", OLD."unit_price"); RETURN NULL;', hash='9c4f1d4daa737ff40e0c618fad121a03592250b6', operation='DELETE', pgid='pgtrigger_delete_delete_b2c62', table='payments', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['purchase', 'refund', 'extra', 'surcharge'])), name='payments_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'surcharge'), _negated=True), models.Q(('lessons_count__isnull', True), ('total_amount__gt', 0), ('parent_payment__isnull', False), ('subscription_index__gte', 1)), _connector='OR'), name='payments_surcharge_shape'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'surcharge'), models.Q(('parent_payment__isnull', True), ('subscription_index__isnull', True)), _connector='OR'), name='payments_parent_only_surcharge'),
        ),
        # Django ставит ON DELETE только на уровне ORM (DEFERRABLE FK без db-каскада).
        # Тесты и другие агенты удаляют строки сырым SQL — нужен каскад в самой БД,
        # иначе удаление родительской оплаты падает на FK-нарушении вместо каскада.
        migrations.RunSQL(
            sql="""
                ALTER TABLE payments
                    DROP CONSTRAINT IF EXISTS payments_parent_payment_id_cff0f28d_fk_payments_id,
                    ADD CONSTRAINT payments_parent_payment_id_cff0f28d_fk_payments_id
                        FOREIGN KEY (parent_payment_id) REFERENCES payments(id)
                        ON DELETE CASCADE;
            """,
            reverse_sql="""
                ALTER TABLE payments
                    DROP CONSTRAINT IF EXISTS payments_parent_payment_id_cff0f28d_fk_payments_id,
                    ADD CONSTRAINT payments_parent_payment_id_cff0f28d_fk_payments_id
                        FOREIGN KEY (parent_payment_id) REFERENCES payments(id);
            """,
        ),
    ]
