# Generated by Django 5.1.4 on 2026-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'teachers',
                'managed': True,
                'indexes': [models.Index(condition=models.Q(('active', True)), fields=['active'], name='teachers_active_idx')],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE teachers ALTER COLUMN created_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE teachers ALTER COLUMN created_at DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE teachers ALTER COLUMN active SET DEFAULT true;",
            reverse_sql="ALTER TABLE teachers ALTER COLUMN active DROP DEFAULT;",
        ),
    ]
