# Generated by Django 5.2.15 on 2026-07-06 08:00

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('name', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='teacher',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "teachers_teacherevent" ("active", "created_at", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone") VALUES (NEW."active", NEW."created_at", NEW."email", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone"); RETURN NULL;', hash='9ccc7e7db8d67965941788dab17ffc4aafa87b04', operation='INSERT', pgid='pgtrigger_insert_insert_94f04', table='teachers', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='teacher',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "teachers_teacherevent" ("active", "created_at", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone") VALUES (NEW."active", NEW."created_at", NEW."email", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone"); RETURN NULL;', hash='bfd8a229d080c12f6b10a61947c27750b57936e2', operation='UPDATE', pgid='pgtrigger_update_update_fbb46', table='teachers', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='teacher',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "teachers_teacherevent" ("active", "created_at", "email", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone") VALUES (OLD."active", OLD."created_at", OLD."email", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone"); RETURN NULL;', hash='e9feffb6a85c7198360cc7984dd5ae15112488fe', operation='DELETE', pgid='pgtrigger_delete_delete_337d8', table='teachers', when='AFTER')),
        ),
        migrations.AddField(
            model_name='teacherevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='teacherevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='teachers.teacher'),
        ),
    ]
