# Generated by Django 5.2.15 on 2026-08-05 09:06

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherevent_teacher_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='teacher',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='teacher',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='teacher',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_service',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='teacherevent',
            name='is_service',
            field=models.BooleanField(db_default=False, default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='teacher',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "teachers_teacherevent" ("active", "created_at", "email", "id", "is_service", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone") VALUES (NEW."active", NEW."created_at", NEW."email", NEW."id", NEW."is_service", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone"); RETURN NULL;', hash='7fa7c8bd2e733bade4b66ad599cde91bd3da7688', operation='INSERT', pgid='pgtrigger_insert_insert_94f04', table='teachers', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='teacher',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "teachers_teacherevent" ("active", "created_at", "email", "id", "is_service", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone") VALUES (NEW."active", NEW."created_at", NEW."email", NEW."id", NEW."is_service", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone"); RETURN NULL;', hash='8e208ade71e798c238d8fbea9d98ed4224e65f71', operation='UPDATE', pgid='pgtrigger_update_update_fbb46', table='teachers', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='teacher',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "teachers_teacherevent" ("active", "created_at", "email", "id", "is_service", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone") VALUES (OLD."active", OLD."created_at", OLD."email", OLD."id", OLD."is_service", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."phone"); RETURN NULL;', hash='9858ae5ecba5b7c845de4fe60521441047631ee9', operation='DELETE', pgid='pgtrigger_delete_delete_337d8', table='teachers', when='AFTER')),
        ),
    ]
