# Generated by Django 5.2.15 on 2026-08-24 20:10

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBoardEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('color', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField()),
                ('category', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], max_length=6)),
            ],
            options={
                'db_table': 'task_stage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskStageEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('label', models.TextField()),
                ('color', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField()),
                ('category', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskBoard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task_board',
                'managed': True,
                'indexes': [models.Index(fields=['sort_order'], name='task_board_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='task_board_name_uq')],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taskboard',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskboardevent" ("created_at", "description", "id", "is_archived", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."created_at", NEW."description", NEW."id", NEW."is_archived", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='809803cb73b16ceade2c5deb731b546e9bcd9d91', operation='INSERT', pgid='pgtrigger_insert_insert_e16b6', table='task_board', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taskboard',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "taskboard_taskboardevent" ("created_at", "description", "id", "is_archived", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."created_at", NEW."description", NEW."id", NEW."is_archived", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='2d18fa82af9fe28d5aeacf3b4a618621699704fa', operation='UPDATE', pgid='pgtrigger_update_update_892c8', table='task_board', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taskboard',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskboardevent" ("created_at", "description", "id", "is_archived", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (OLD."created_at", OLD."description", OLD."id", OLD."is_archived", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sort_order"); RETURN NULL;', hash='9acab8dc4882a12442e560e730636962a51ab87f', operation='DELETE', pgid='pgtrigger_delete_delete_8f002', table='task_board', when='AFTER')),
        ),
        migrations.AddField(
            model_name='taskboardevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='taskboardevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='taskboard.taskboard'),
        ),
        migrations.AddField(
            model_name='taskstage',
            name='board',
            field=models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='taskboard.taskboard'),
        ),
        migrations.AddField(
            model_name='taskstageevent',
            name='board',
            field=models.ForeignKey(db_column='board_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='taskboard.taskboard'),
        ),
        migrations.AddField(
            model_name='taskstageevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='taskstageevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='taskboard.taskstage'),
        ),
        migrations.AddIndex(
            model_name='taskstage',
            index=models.Index(fields=['board', 'sort_order'], name='task_stage_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskstage',
            constraint=models.UniqueConstraint(fields=('board', 'label'), name='task_stage_board_label_uq'),
        ),
        migrations.AddConstraint(
            model_name='taskstage',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['open', 'closed'])), name='task_stage_category_check'),
        ),
        migrations.AddConstraint(
            model_name='taskstage',
            constraint=models.CheckConstraint(condition=models.Q(('color__isnull', True), ('color__regex', '^#[0-9a-fA-F]{6}$'), _connector='OR'), name='task_stage_color_check'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taskstage',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskstageevent" ("board_id", "category", "color", "id", "label", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."board_id", NEW."category", NEW."color", NEW."id", NEW."label", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='b16b7aa1092abb950b13e43720e90885015016e9', operation='INSERT', pgid='pgtrigger_insert_insert_cefa7', table='task_stage', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taskstage',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "taskboard_taskstageevent" ("board_id", "category", "color", "id", "label", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."board_id", NEW."category", NEW."color", NEW."id", NEW."label", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='521c3bd92598819f31b4969f10230b6698232685', operation='UPDATE', pgid='pgtrigger_update_update_ba0c9', table='task_stage', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taskstage',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskstageevent" ("board_id", "category", "color", "id", "label", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (OLD."board_id", OLD."category", OLD."color", OLD."id", OLD."label", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sort_order"); RETURN NULL;', hash='1f99f0cc7728e66a7e28adc1c5cf69f7256f09b5', operation='DELETE', pgid='pgtrigger_delete_delete_55c40', table='task_stage', when='AFTER')),
        ),
    ]
