# Generated by Django 5.2.15 on 2026-08-24 20:18

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove_group_insert_insert_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('students', '0016_drop_enrollment_status'),
        ('taskboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTagEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('label', models.TextField()),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'task_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskTypeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('label', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий')], default='normal', max_length=6)),
                ('resolution', models.CharField(blank=True, choices=[('done', 'Выполнено'), ('cancelled', 'Отменено'), ('irrelevant', 'Неактуально')], max_length=10, null=True)),
                ('stage_entered_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, db_column='assignee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='taskboard.taskboard')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='groups.group')),
                ('stage', models.ForeignKey(db_column='stage_id', on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='taskboard.taskstage')),
                ('student', models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='students.student')),
            ],
            options={
                'db_table': 'task',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('stage_change', 'Смена стадии'), ('assign', 'Смена исполнителя'), ('comment', 'Комментарий'), ('system', 'Системная запись')], max_length=12)),
                ('text', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activity', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='taskboard.task')),
            ],
            options={
                'db_table': 'task_activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskActivityEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('stage_change', 'Смена стадии'), ('assign', 'Смена исполнителя'), ('comment', 'Комментарий'), ('system', 'Системная запись')], max_length=12)),
                ('text', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, db_column='author_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='taskboard.taskactivity')),
                ('task', models.ForeignKey(db_column='task_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='taskboard.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий')], default='normal', max_length=6)),
                ('resolution', models.CharField(blank=True, choices=[('done', 'Выполнено'), ('cancelled', 'Отменено'), ('irrelevant', 'Неактуально')], max_length=10, null=True)),
                ('stage_entered_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, db_column='assignee_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(db_column='board_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='taskboard.taskboard')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, db_column='group_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='groups.group')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='taskboard.task')),
                ('stage', models.ForeignKey(db_column='stage_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='taskboard.taskstage')),
                ('student', models.ForeignKey(blank=True, db_column='student_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_tag',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('label',), name='task_tag_label_uq'), models.CheckConstraint(condition=models.Q(('color__isnull', True), ('color__regex', '^#[0-9a-fA-F]{6}$'), _connector='OR'), name='task_tag_color_check')],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='task_tag_link', related_name='tasks', to='taskboard.tasktag'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tasktag',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_tasktagevent" ("color", "id", "label", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."color", NEW."id", NEW."label", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='8b29c21c2a593a2f3398a238519b4541d68eeb53', operation='INSERT', pgid='pgtrigger_insert_insert_bed34', table='task_tag', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tasktag',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "taskboard_tasktagevent" ("color", "id", "label", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."color", NEW."id", NEW."label", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='153161bf11ffe89f3f36a57fe52f8c153a96f1fd', operation='UPDATE', pgid='pgtrigger_update_update_59617', table='task_tag', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tasktag',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_tasktagevent" ("color", "id", "label", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."color", OLD."id", OLD."label", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='dd9a5a4cb97bc67225f6669418ec779f61f5f5da', operation='DELETE', pgid='pgtrigger_delete_delete_71467', table='task_tag', when='AFTER')),
        ),
        migrations.AddField(
            model_name='tasktagevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='tasktagevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='taskboard.tasktag'),
        ),
        migrations.AddConstraint(
            model_name='tasktype',
            constraint=models.UniqueConstraint(fields=('label',), name='task_type_label_uq'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='task_type',
            field=models.ForeignKey(blank=True, db_column='task_type_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='taskboard.tasktype'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, db_column='task_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='taskboard.tasktype'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tasktype',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_tasktypeevent" ("id", "label", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."id", NEW."label", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='501ce7dd16627176e781a3f52a03ed5d27ce27ca', operation='INSERT', pgid='pgtrigger_insert_insert_7bba7', table='task_type', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tasktype',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "taskboard_tasktypeevent" ("id", "label", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."id", NEW."label", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='639fe6a6d632b443da2ab02ba4282f2b1bd4b865', operation='UPDATE', pgid='pgtrigger_update_update_20e40', table='task_type', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tasktype',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_tasktypeevent" ("id", "label", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (OLD."id", OLD."label", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sort_order"); RETURN NULL;', hash='93ac1953d45b634f4bd7e66bb0171901554e5361', operation='DELETE', pgid='pgtrigger_delete_delete_09a26', table='task_type', when='AFTER')),
        ),
        migrations.AddField(
            model_name='tasktypeevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='tasktypeevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='taskboard.tasktype'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['task', 'created_at'], name='task_activity_task_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskactivity',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['stage_change', 'assign', 'comment', 'system'])), name='task_activity_kind_check'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taskactivity',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskactivityevent" ("author_id", "created_at", "id", "kind", "meta", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "task_id", "text") VALUES (NEW."author_id", NEW."created_at", NEW."id", NEW."kind", NEW."meta", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."task_id", NEW."text"); RETURN NULL;', hash='94f87f476ab7d13cbf94113fdb4dfe30c652d4dc', operation='INSERT', pgid='pgtrigger_insert_insert_50c00', table='task_activity', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taskactivity',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "taskboard_taskactivityevent" ("author_id", "created_at", "id", "kind", "meta", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "task_id", "text") VALUES (NEW."author_id", NEW."created_at", NEW."id", NEW."kind", NEW."meta", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."task_id", NEW."text"); RETURN NULL;', hash='034a9536b06ebd5da1c64ba398a97ae12f9e2808', operation='UPDATE', pgid='pgtrigger_update_update_342bd', table='task_activity', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taskactivity',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskactivityevent" ("author_id", "created_at", "id", "kind", "meta", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "task_id", "text") VALUES (OLD."author_id", OLD."created_at", OLD."id", OLD."kind", OLD."meta", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."task_id", OLD."text"); RETURN NULL;', hash='0f6287250213572c047beb1113c16ada6f06b15c', operation='DELETE', pgid='pgtrigger_delete_delete_3df14', table='task_activity', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'stage'], name='task_board_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('closed_at__isnull', True)), fields=['assignee'], name='task_assignee_open_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('student__isnull', False)), fields=['student'], name='task_student_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('closed_at__isnull', True)), fields=['due_date'], name='task_due_open_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['low', 'normal', 'high'])), name='task_priority_check'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('resolution__isnull', True), ('resolution__in', ['done', 'cancelled', 'irrelevant']), _connector='OR'), name='task_resolution_check'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('resolution__isnull', True)), models.Q(('closed_at__isnull', False), ('resolution__isnull', False)), _connector='OR'), name='task_closed_resolution_check'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskevent" ("assignee_id", "board_id", "closed_at", "created_at", "created_by_id", "description", "due_date", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "resolution", "stage_entered_at", "stage_id", "student_id", "task_type_id", "title", "updated_at") VALUES (NEW."assignee_id", NEW."board_id", NEW."closed_at", NEW."created_at", NEW."created_by_id", NEW."description", NEW."due_date", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priority", NEW."resolution", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."task_type_id", NEW."title", NEW."updated_at"); RETURN NULL;', hash='2c64285425ab6f15801f04687936f6fcd1215943', operation='INSERT', pgid='pgtrigger_insert_insert_c011c', table='task', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "taskboard_taskevent" ("assignee_id", "board_id", "closed_at", "created_at", "created_by_id", "description", "due_date", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "resolution", "stage_entered_at", "stage_id", "student_id", "task_type_id", "title", "updated_at") VALUES (NEW."assignee_id", NEW."board_id", NEW."closed_at", NEW."created_at", NEW."created_by_id", NEW."description", NEW."due_date", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priority", NEW."resolution", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."task_type_id", NEW."title", NEW."updated_at"); RETURN NULL;', hash='3ebfee61b5204c3a9e092c1f74e55746dd053703', operation='UPDATE', pgid='pgtrigger_update_update_5ed1e', table='task', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskevent" ("assignee_id", "board_id", "closed_at", "created_at", "created_by_id", "description", "due_date", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "resolution", "stage_entered_at", "stage_id", "student_id", "task_type_id", "title", "updated_at") VALUES (OLD."assignee_id", OLD."board_id", OLD."closed_at", OLD."created_at", OLD."created_by_id", OLD."description", OLD."due_date", OLD."group_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."priority", OLD."resolution", OLD."stage_entered_at", OLD."stage_id", OLD."student_id", OLD."task_type_id", OLD."title", OLD."updated_at"); RETURN NULL;', hash='07cd2466da4c3c32176d0cdd6538829c0bc7d2fb', operation='DELETE', pgid='pgtrigger_delete_delete_b29ea', table='task', when='AFTER')),
        ),
    ]
