# Generated by Django 5.2.15 on 2026-08-27 07:14

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0003_seed_default_board'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='taskboard',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='taskboard',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='taskboard',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='taskboard',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='taskboardevent',
            name='is_archived',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taskboard',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskboardevent" ("created_at", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."created_at", NEW."description", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='b1cd7495bf927c28526a68cc50c6f7a2fa4f2732', operation='INSERT', pgid='pgtrigger_insert_insert_e16b6', table='task_board', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taskboard',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "taskboard_taskboardevent" ("created_at", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (NEW."created_at", NEW."description", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sort_order"); RETURN NULL;', hash='5273a8147e6b4dc4ddf15c5f96cf03d2fc1da757', operation='UPDATE', pgid='pgtrigger_update_update_892c8', table='task_board', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='taskboard',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskboardevent" ("created_at", "description", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sort_order") VALUES (OLD."created_at", OLD."description", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sort_order"); RETURN NULL;', hash='143788fada3eda5e65bfb896c897fba93ff9340f', operation='DELETE', pgid='pgtrigger_delete_delete_8f002', table='task_board', when='AFTER')),
        ),
    ]
