# Generated by Django 5.2.15 on 2026-08-27 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0004_remove_taskboard_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, db_table='task_assignee', related_name='assigned_tasks_m2m', to=settings.AUTH_USER_MODEL),
        ),
    ]
