# Generated by Django 5.2.15 on 2026-08-27 07:43

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0006_backfill_task_assignees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='task',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='task',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='task',
            name='delete_delete',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_assignee_open_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='taskevent',
            name='assignee',
        ),
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, db_table='task_assignee', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskevent" ("board_id", "closed_at", "created_at", "created_by_id", "description", "due_date", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "resolution", "stage_entered_at", "stage_id", "student_id", "task_type_id", "title", "updated_at") VALUES (NEW."board_id", NEW."closed_at", NEW."created_at", NEW."created_by_id", NEW."description", NEW."due_date", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priority", NEW."resolution", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."task_type_id", NEW."title", NEW."updated_at"); RETURN NULL;', hash='4cf5ffd890797f1892bd60699712e74b83b30254', operation='INSERT', pgid='pgtrigger_insert_insert_c011c', table='task', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "taskboard_taskevent" ("board_id", "closed_at", "created_at", "created_by_id", "description", "due_date", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "resolution", "stage_entered_at", "stage_id", "student_id", "task_type_id", "title", "updated_at") VALUES (NEW."board_id", NEW."closed_at", NEW."created_at", NEW."created_by_id", NEW."description", NEW."due_date", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priority", NEW."resolution", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."task_type_id", NEW."title", NEW."updated_at"); RETURN NULL;', hash='d5f81bd07350168c2c6b392f9fcbbf7ff21881fc', operation='UPDATE', pgid='pgtrigger_update_update_5ed1e', table='task', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskevent" ("board_id", "closed_at", "created_at", "created_by_id", "description", "due_date", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "resolution", "stage_entered_at", "stage_id", "student_id", "task_type_id", "title", "updated_at") VALUES (OLD."board_id", OLD."closed_at", OLD."created_at", OLD."created_by_id", OLD."description", OLD."due_date", OLD."group_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."priority", OLD."resolution", OLD."stage_entered_at", OLD."stage_id", OLD."student_id", OLD."task_type_id", OLD."title", OLD."updated_at"); RETURN NULL;', hash='d99fa27c328072de62aa5e05fc5b123304840e1d', operation='DELETE', pgid='pgtrigger_delete_delete_b29ea', table='task', when='AFTER')),
        ),
    ]
