# Generated by Django 5.2.15 on 2026-08-28 14:25

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0007_drop_task_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktagevent',
            name='pgh_obj',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tasktagevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='tasktypeevent',
            name='pgh_obj',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='taskevent',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='tasktypeevent',
            name='pgh_context',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='task',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='task',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='task',
            name='delete_delete',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskevent" ("board_id", "closed_at", "created_at", "created_by_id", "description", "due_date", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "resolution", "stage_entered_at", "stage_id", "student_id", "title", "updated_at") VALUES (NEW."board_id", NEW."closed_at", NEW."created_at", NEW."created_by_id", NEW."description", NEW."due_date", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priority", NEW."resolution", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."title", NEW."updated_at"); RETURN NULL;', hash='9d0bebbfea1a22d38b73d510d01d1bff37764679', operation='INSERT', pgid='pgtrigger_insert_insert_c011c', table='task', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "taskboard_taskevent" ("board_id", "closed_at", "created_at", "created_by_id", "description", "due_date", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "resolution", "stage_entered_at", "stage_id", "student_id", "title", "updated_at") VALUES (NEW."board_id", NEW."closed_at", NEW."created_at", NEW."created_by_id", NEW."description", NEW."due_date", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priority", NEW."resolution", NEW."stage_entered_at", NEW."stage_id", NEW."student_id", NEW."title", NEW."updated_at"); RETURN NULL;', hash='0af90aed29ef23805353d1e1e56196ebdb69f602', operation='UPDATE', pgid='pgtrigger_update_update_5ed1e', table='task', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "taskboard_taskevent" ("board_id", "closed_at", "created_at", "created_by_id", "description", "due_date", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "resolution", "stage_entered_at", "stage_id", "student_id", "title", "updated_at") VALUES (OLD."board_id", OLD."closed_at", OLD."created_at", OLD."created_by_id", OLD."description", OLD."due_date", OLD."group_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."priority", OLD."resolution", OLD."stage_entered_at", OLD."stage_id", OLD."student_id", OLD."title", OLD."updated_at"); RETURN NULL;', hash='5b3ab65180ed57dbe6ce5c68a245dce187b3897b', operation='DELETE', pgid='pgtrigger_delete_delete_b29ea', table='task', when='AFTER')),
        ),
        migrations.DeleteModel(
            name='TaskTag',
        ),
        migrations.DeleteModel(
            name='TaskTagEvent',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
        migrations.DeleteModel(
            name='TaskTypeEvent',
        ),
    ]
