# Generated by Django 5.1.4 on 2026-06-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncFailure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('operation', models.TextField()),
                ('payload', models.JSONField()),
                ('error_message', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_failures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('actor_email', models.TextField(blank=True, null=True)),
                ('event', models.TextField()),
                ('ip', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_events', to='accounts.account')),
            ],
            options={
                'db_table': 'security_audit_log',
                'managed': True,
                'indexes': [models.Index(fields=['-occurred_at'], name='sec_audit_log_occurred_idx'), models.Index(fields=['account', '-occurred_at'], name='security_audit_log_account_idx')],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE security_audit_log ALTER COLUMN occurred_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE security_audit_log ALTER COLUMN occurred_at DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE sync_failures ALTER COLUMN occurred_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE sync_failures ALTER COLUMN occurred_at DROP DEFAULT;",
        ),
    ]
