# Generated by Django 5.1.4 on 2026-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('sheet_name', models.TextField()),
                ('is_individual', models.BooleanField()),
                ('total_lessons', models.IntegerField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('subscription_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'directions',
                'managed': True,
                'indexes': [models.Index(condition=models.Q(('active', True)), fields=['active'], name='directions_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_lessons__isnull', True), ('total_lessons__gte', 0), _connector='OR'), name='directions_total_lessons_check'), models.CheckConstraint(condition=models.Q(('color__isnull', True), ('color__regex', '^#[0-9a-fA-F]{6}$'), _connector='OR'), name='directions_color_check'), models.CheckConstraint(condition=models.Q(('subscription_price__isnull', True), ('subscription_price__gte', 0), _connector='OR'), name='directions_subscription_price_check')],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE directions ALTER COLUMN active SET DEFAULT true;",
            reverse_sql="ALTER TABLE directions ALTER COLUMN active DROP DEFAULT;",
        ),
    ]
