# Generated by Django 5.2.15 on 2026-07-06 07:57

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('name', models.TextField()),
                ('sheet_name', models.TextField()),
                ('is_individual', models.BooleanField()),
                ('total_lessons', models.IntegerField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('subscription_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='direction',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "directions_directionevent" ("active", "color", "id", "is_individual", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sheet_name", "subscription_price", "total_lessons") VALUES (NEW."active", NEW."color", NEW."id", NEW."is_individual", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sheet_name", NEW."subscription_price", NEW."total_lessons"); RETURN NULL;', hash='4f04a88c2503981c1bbd9e21409735f3cfdb60c3', operation='INSERT', pgid='pgtrigger_insert_insert_7dd8c', table='directions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='direction',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "directions_directionevent" ("active", "color", "id", "is_individual", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sheet_name", "subscription_price", "total_lessons") VALUES (NEW."active", NEW."color", NEW."id", NEW."is_individual", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sheet_name", NEW."subscription_price", NEW."total_lessons"); RETURN NULL;', hash='3f9d5043bcc37ad8471e4dd18f26a84e71dbb8c7', operation='UPDATE', pgid='pgtrigger_update_update_ac12f', table='directions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='direction',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "directions_directionevent" ("active", "color", "id", "is_individual", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sheet_name", "subscription_price", "total_lessons") VALUES (OLD."active", OLD."color", OLD."id", OLD."is_individual", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sheet_name", OLD."subscription_price", OLD."total_lessons"); RETURN NULL;', hash='4cdb7f644e6b717748c754a1126e875607df80ca', operation='DELETE', pgid='pgtrigger_delete_delete_2dfbc', table='directions', when='AFTER')),
        ),
        migrations.AddField(
            model_name='directionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='directionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='directions.direction'),
        ),
    ]
