# Generated by Django 5.2.15 on 2026-07-09 16:05

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_directionevent_direction_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='direction',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='direction',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='direction',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='sheet_name',
        ),
        migrations.RemoveField(
            model_name='directionevent',
            name='sheet_name',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='direction',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "directions_directionevent" ("active", "color", "id", "is_individual", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "subscription_price", "total_lessons") VALUES (NEW."active", NEW."color", NEW."id", NEW."is_individual", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."subscription_price", NEW."total_lessons"); RETURN NULL;', hash='8825ba54b07db50688a31d00927db3bed1b32e2c', operation='INSERT', pgid='pgtrigger_insert_insert_7dd8c', table='directions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='direction',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "directions_directionevent" ("active", "color", "id", "is_individual", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "subscription_price", "total_lessons") VALUES (NEW."active", NEW."color", NEW."id", NEW."is_individual", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."subscription_price", NEW."total_lessons"); RETURN NULL;', hash='eaeca1dd980ab87c97156cf835c72eaf1adcf68a', operation='UPDATE', pgid='pgtrigger_update_update_ac12f', table='directions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='direction',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "directions_directionevent" ("active", "color", "id", "is_individual", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "subscription_price", "total_lessons") VALUES (OLD."active", OLD."color", OLD."id", OLD."is_individual", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."subscription_price", OLD."total_lessons"); RETURN NULL;', hash='d8fe70173e3b37b41661b0275efc883d4bce90e5', operation='DELETE', pgid='pgtrigger_delete_delete_2dfbc', table='directions', when='AFTER')),
        ),
    ]
