# Generated by Django 5.2.15 on 2026-07-23 19:18

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_remove_direction_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='direction',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='direction',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='direction',
            name='delete_delete',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='is_individual',
        ),
        migrations.RemoveField(
            model_name='directionevent',
            name='is_individual',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='direction',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "directions_directionevent" ("active", "color", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "subscription_price", "total_lessons") VALUES (NEW."active", NEW."color", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."subscription_price", NEW."total_lessons"); RETURN NULL;', hash='cf24facd8a0e5f410431fa2adacaae14e9a7f214', operation='INSERT', pgid='pgtrigger_insert_insert_7dd8c', table='directions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='direction',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "directions_directionevent" ("active", "color", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "subscription_price", "total_lessons") VALUES (NEW."active", NEW."color", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."subscription_price", NEW."total_lessons"); RETURN NULL;', hash='1d2d9fef3238af249aa4d5280c3e84cd76902449', operation='UPDATE', pgid='pgtrigger_update_update_ac12f', table='directions', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='direction',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "directions_directionevent" ("active", "color", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "subscription_price", "total_lessons") VALUES (OLD."active", OLD."color", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."subscription_price", OLD."total_lessons"); RETURN NULL;', hash='06106eaad914d43d9d2bcb95380e56c7ca68ee38', operation='DELETE', pgid='pgtrigger_delete_delete_2dfbc', table='directions', when='AFTER')),
        ),
    ]
