# Generated by Django 5.2.15 on 2026-08-06 17:20

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.JSONField(default=dict)),
                ('plain_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=20)),
                ('reader_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('position', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_documents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('original_name', models.TextField()),
                ('mime', models.CharField(max_length=50)),
                ('byte_size', models.BigIntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('original_path', models.TextField()),
                ('optimized_path', models.TextField(blank=True, null=True)),
                ('thumb_path', models.TextField(blank=True, null=True)),
                ('optimize_state', models.CharField(choices=[('pending', 'В очереди'), ('ready', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeImageUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_usages', to='knowledge.knowledgedocument')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='knowledge.knowledgeimage')),
            ],
            options={
                'db_table': 'knowledge_image_usages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(unique=True)),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_sections',
                'managed': True,
                'indexes': [models.Index(condition=models.Q(('active', True)), fields=['position'], name='knowledge_sect_pos_idx')],
            },
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='knowledge.knowledgesection'),
        ),
        migrations.AddIndex(
            model_name='knowledgeimage',
            index=models.Index(condition=models.Q(('optimize_state', 'pending')), fields=['optimize_state'], name='knowledge_img_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeimageusage',
            constraint=models.UniqueConstraint(fields=('image', 'document'), name='knowledge_img_usage_uq'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(condition=models.Q(('active', True)), fields=['section', 'position'], name='knowledge_doc_secpos_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['reader_roles'], name='knowledge_doc_roles_gin'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(condition=models.Q(('status', 'published')), fields=['status'], name='knowledge_doc_pub_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published'])), name='knowledge_doc_status_check'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.CheckConstraint(condition=models.Q(('reader_roles__contained_by', ['teacher', 'manager', 'admin', 'superadmin'])), name='knowledge_doc_roles_check'),
        ),
    ]
