# Generated by Django 5.2.15 on 2026-08-07 06:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocumentVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.JSONField(default=dict)),
                ('size_delta', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knowledge_document_versions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocumentView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knowledge_document_views',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knowledge_favorites',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='search_tsv',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('title', 'plain_text', config='russian'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_tsv'], name='knowledge_doc_fts_gin'),
        ),
        migrations.AddField(
            model_name='knowledgedocumentversion',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgedocumentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.knowledgedocument'),
        ),
        migrations.AddField(
            model_name='knowledgedocumentview',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgedocumentview',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='knowledge.knowledgedocument'),
        ),
        migrations.AddField(
            model_name='knowledgefavorite',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgefavorite',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='knowledge.knowledgedocument'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocumentversion',
            index=models.Index(fields=['document', '-created_at'], name='knowledge_ver_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocumentview',
            index=models.Index(fields=['account', '-created_at'], name='knowledge_view_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocumentview',
            constraint=models.UniqueConstraint(fields=('document', 'account', 'day'), name='knowledge_view_uq'),
        ),
        migrations.AddConstraint(
            model_name='knowledgefavorite',
            constraint=models.UniqueConstraint(fields=('account', 'document'), name='knowledge_fav_uq'),
        ),
    ]
