# Generated by Django 5.2.15 on 2026-08-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgedocumentversion_knowledgedocumentview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='views_count',
        ),
        migrations.DeleteModel(
            name='KnowledgeDocumentView',
        ),
    ]
