# Generated by Django 5.2.15 on 2026-08-12 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_drop_document_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('original_name', models.TextField()),
                ('mime', models.CharField(max_length=100)),
                ('byte_size', models.BigIntegerField()),
                ('path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_files',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFileUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_usages', to='knowledge.knowledgedocument')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='knowledge.knowledgefile')),
            ],
            options={
                'db_table': 'knowledge_file_usages',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('file', 'document'), name='knowledge_file_usage_uq')],
            },
        ),
    ]
