# Generated by Django 5.1.4 on 2026-06-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'discounts',
                'managed': True,
                'indexes': [models.Index(fields=['active'], name='discounts_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('amount__lte', 1)), name='discounts_amount_check'),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE discounts ALTER COLUMN created_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE discounts ALTER COLUMN created_at DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE discounts ALTER COLUMN active SET DEFAULT true;",
            reverse_sql="ALTER TABLE discounts ALTER COLUMN active DROP DEFAULT;",
        ),
    ]
