# Generated by Django 5.2.15 on 2026-07-06 08:00

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('name', models.TextField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='discount',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discounts_discountevent" ("active", "amount", "created_at", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."amount", NEW."created_at", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='03b6f502aaf3d375b77e7433c401dac6640d6e6c', operation='INSERT', pgid='pgtrigger_insert_insert_5ce18', table='discounts', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='discount',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "discounts_discountevent" ("active", "amount", "created_at", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."active", NEW."amount", NEW."created_at", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='87acf41b2dbf314f5699c1f262831615f44980fa', operation='UPDATE', pgid='pgtrigger_update_update_7bd72', table='discounts', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='discount',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "discounts_discountevent" ("active", "amount", "created_at", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."active", OLD."amount", OLD."created_at", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='af6ed37010f204eba3c404bba6d651e3438b04ce', operation='DELETE', pgid='pgtrigger_delete_delete_c1f10', table='discounts', when='AFTER')),
        ),
        migrations.AddField(
            model_name='discountevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='discountevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='discounts.discount'),
        ),
    ]
