# Generated by Django 5.1.4 on 2026-06-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('role', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('twofa_method', models.TextField(blank=True, null=True)),
                ('twofa_secret', models.TextField(blank=True, null=True)),
                ('twofa_enabled', models.BooleanField(default=False)),
                ('twofa_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_login_count', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('teacher', models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='teachers.teacher')),
            ],
            options={
                'db_table': 'accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountRecoveryCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_hash', models.TextField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='accounts.account')),
            ],
            options={
                'db_table': 'account_recovery_codes',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['teacher', 'manager', 'admin'])), name='accounts_role_check'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('twofa_method__in', ['totp', 'email'])), name='accounts_twofa_method_check'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'teacher'), ('teacher__isnull', False)), models.Q(models.Q(('role', 'teacher'), _negated=True), ('teacher__isnull', True)), _connector='OR'), name='accounts_check'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('twofa_method', 'totp'), _negated=True), ('twofa_secret__isnull', False), _connector='OR'), name='accounts_check1'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher__isnull', False)), fields=('teacher',), name='accounts_teacher_id_uq'),
        ),
        migrations.AddIndex(
            model_name='accountrecoverycode',
            index=models.Index(fields=['account'], name='arc_account_idx'),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts ALTER COLUMN created_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE accounts ALTER COLUMN created_at DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts ALTER COLUMN active SET DEFAULT true;",
            reverse_sql="ALTER TABLE accounts ALTER COLUMN active DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts ALTER COLUMN failed_login_count SET DEFAULT 0;",
            reverse_sql="ALTER TABLE accounts ALTER COLUMN failed_login_count DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts ALTER COLUMN twofa_enabled SET DEFAULT false;",
            reverse_sql="ALTER TABLE accounts ALTER COLUMN twofa_enabled DROP DEFAULT;",
        ),
    ]
