# Generated by Django 5.1.4 on 2026-06-14 16:41

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_migrate_to_abstractuser'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', apps.accounts.models.AccountManager()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='account',
            name='failed_login_count',
            field=models.IntegerField(default=0, verbose_name='failed login count'),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='account',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='locked until'),
        ),
        migrations.AlterField(
            model_name='account',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='teachers.teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='account',
            name='token_version',
            field=models.IntegerField(default=0, verbose_name='token version'),
        ),
        migrations.AlterField(
            model_name='account',
            name='twofa_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2FA confirmed at'),
        ),
        migrations.AlterField(
            model_name='account',
            name='twofa_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA enabled'),
        ),
        migrations.AlterField(
            model_name='account',
            name='twofa_method',
            field=models.CharField(blank=True, choices=[('totp', 'TOTP'), ('email', 'Email')], max_length=10, null=True, verbose_name='2FA method'),
        ),
        migrations.AlterField(
            model_name='account',
            name='twofa_secret',
            field=models.TextField(blank=True, null=True, verbose_name='2FA secret'),
        ),
        migrations.AlterField(
            model_name='accountinvite',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountrecoverycode',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
