# Generated by Django 5.2.15 on 2026-07-06 08:00

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_options_alter_account_managers_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('role', models.CharField(choices=[('teacher', 'Учитель'), ('manager', 'Менеджер'), ('admin', 'Администратор')], max_length=20, verbose_name='role')),
                ('twofa_method', models.CharField(blank=True, choices=[('totp', 'TOTP'), ('email', 'Email')], max_length=10, null=True, verbose_name='2FA method')),
                ('twofa_enabled', models.BooleanField(default=False, verbose_name='2FA enabled')),
                ('twofa_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='2FA confirmed at')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounts_accountevent" ("date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "teacher_id", "twofa_confirmed_at", "twofa_enabled", "twofa_method") VALUES (NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role", NEW."teacher_id", NEW."twofa_confirmed_at", NEW."twofa_enabled", NEW."twofa_method"); RETURN NULL;', hash='0402edcfd650998dbd9d5fea49cccf7ea5842988', operation='INSERT', pgid='pgtrigger_insert_insert_8b982', table='accounts', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."date_joined" IS DISTINCT FROM (NEW."date_joined") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."first_name" IS DISTINCT FROM (NEW."first_name") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."last_name" IS DISTINCT FROM (NEW."last_name") OR OLD."role" IS DISTINCT FROM (NEW."role") OR OLD."teacher_id" IS DISTINCT FROM (NEW."teacher_id") OR OLD."twofa_confirmed_at" IS DISTINCT FROM (NEW."twofa_confirmed_at") OR OLD."twofa_enabled" IS DISTINCT FROM (NEW."twofa_enabled") OR OLD."twofa_method" IS DISTINCT FROM (NEW."twofa_method"))', func='INSERT INTO "accounts_accountevent" ("date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "teacher_id", "twofa_confirmed_at", "twofa_enabled", "twofa_method") VALUES (NEW."date_joined", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role", NEW."teacher_id", NEW."twofa_confirmed_at", NEW."twofa_enabled", NEW."twofa_method"); RETURN NULL;', hash='91c163f7a2a414327017845295c3aa86f70bd41d', operation='UPDATE', pgid='pgtrigger_update_update_834ae', table='accounts', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounts_accountevent" ("date_joined", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "teacher_id", "twofa_confirmed_at", "twofa_enabled", "twofa_method") VALUES (OLD."date_joined", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."role", OLD."teacher_id", OLD."twofa_confirmed_at", OLD."twofa_enabled", OLD."twofa_method"); RETURN NULL;', hash='6033570d42785ae3150532a8798ac9fff056d748', operation='DELETE', pgid='pgtrigger_delete_delete_f7f6a', table='accounts', when='AFTER')),
        ),
        migrations.AddField(
            model_name='accountevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='accountevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountevent',
            name='teacher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='teachers.teacher', verbose_name='teacher'),
        ),
    ]
