# Generated by Django 5.2.15 on 2026-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_options_alter_account_managers_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='accounts_role_check',
        ),
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('manager', 'Менеджер'), ('admin', 'Администратор'), ('superadmin', 'Суперадминистратор')], max_length=20, verbose_name='role'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['teacher', 'manager', 'admin', 'superadmin'])), name='accounts_role_check'),
        ),
    ]
