# Generated by Django 5.2.15 on 2026-07-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accountevent_account_insert_insert_and_more'),
        ('accounts', '0008_promote_admins_to_superadmin'),
    ]

    operations = [
    ]
