# Generated by Django 5.2.15 on 2026-07-07 15:08

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260707_1808'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='account',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='account',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='account',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='accountevent',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='accountevent',
            name='role',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('manager', 'Менеджер'), ('admin', 'Администратор'), ('superadmin', 'Суперадминистратор')], max_length=20, verbose_name='role'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounts_accountevent" ("date_joined", "email", "first_name", "full_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "teacher_id", "twofa_confirmed_at", "twofa_enabled", "twofa_method") VALUES (NEW."date_joined", NEW."email", NEW."first_name", NEW."full_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role", NEW."teacher_id", NEW."twofa_confirmed_at", NEW."twofa_enabled", NEW."twofa_method"); RETURN NULL;', hash='9ee5cebdafe00f1e9c3c153f7ea291b880333c43', operation='INSERT', pgid='pgtrigger_insert_insert_8b982', table='accounts', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."date_joined" IS DISTINCT FROM (NEW."date_joined") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."first_name" IS DISTINCT FROM (NEW."first_name") OR OLD."full_name" IS DISTINCT FROM (NEW."full_name") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."last_name" IS DISTINCT FROM (NEW."last_name") OR OLD."role" IS DISTINCT FROM (NEW."role") OR OLD."teacher_id" IS DISTINCT FROM (NEW."teacher_id") OR OLD."twofa_confirmed_at" IS DISTINCT FROM (NEW."twofa_confirmed_at") OR OLD."twofa_enabled" IS DISTINCT FROM (NEW."twofa_enabled") OR OLD."twofa_method" IS DISTINCT FROM (NEW."twofa_method"))', func='INSERT INTO "accounts_accountevent" ("date_joined", "email", "first_name", "full_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "teacher_id", "twofa_confirmed_at", "twofa_enabled", "twofa_method") VALUES (NEW."date_joined", NEW."email", NEW."first_name", NEW."full_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role", NEW."teacher_id", NEW."twofa_confirmed_at", NEW."twofa_enabled", NEW."twofa_method"); RETURN NULL;', hash='3db1d78e5b7cda5c647871f464afc11f6c929b2e', operation='UPDATE', pgid='pgtrigger_update_update_834ae', table='accounts', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounts_accountevent" ("date_joined", "email", "first_name", "full_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "teacher_id", "twofa_confirmed_at", "twofa_enabled", "twofa_method") VALUES (OLD."date_joined", OLD."email", OLD."first_name", OLD."full_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."role", OLD."teacher_id", OLD."twofa_confirmed_at", OLD."twofa_enabled", OLD."twofa_method"); RETURN NULL;', hash='ae6ace06d67682b5f8d44b569cb7e26c9061edfc', operation='DELETE', pgid='pgtrigger_delete_delete_f7f6a', table='accounts', when='AFTER')),
        ),
    ]
