# Generated by Django 5.1.4 on 2026-06-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directions', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('is_individual', models.BooleanField()),
                ('lesson_duration_minutes', models.IntegerField(default=90)),
                ('lessons_per_week', models.IntegerField(default=1)),
                ('group_start_date', models.DateField(blank=True, null=True)),
                ('vk_chat', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('direction', models.ForeignKey(db_column='direction_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='directions.direction')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='teachers.teacher')),
            ],
            options={
                'db_table': 'groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupScheduleSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='groups.group')),
            ],
            options={
                'db_table': 'group_schedule_slots',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(condition=models.Q(('active', True)), fields=['active'], name='groups_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('lesson_duration_minutes__in', [45, 60, 90])), name='groups_lesson_duration_minutes_check'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('lessons_per_week__gte', 1), ('lessons_per_week__lte', 7)), name='groups_lessons_per_week_check'),
        ),
        migrations.AddIndex(
            model_name='groupscheduleslot',
            index=models.Index(fields=['day_of_week', 'start_time'], name='gss_dow_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupscheduleslot',
            constraint=models.UniqueConstraint(fields=('group', 'day_of_week', 'start_time'), name='group_schedule_slots_group_id_day_of_week_start_time_key'),
        ),
        migrations.AddConstraint(
            model_name='groupscheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='group_schedule_slots_day_of_week_check'),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE groups ALTER COLUMN created_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE groups ALTER COLUMN created_at DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE groups ALTER COLUMN active SET DEFAULT true;",
            reverse_sql="ALTER TABLE groups ALTER COLUMN active DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE groups ALTER COLUMN lesson_duration_minutes SET DEFAULT 90;",
            reverse_sql="ALTER TABLE groups ALTER COLUMN lesson_duration_minutes DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE groups ALTER COLUMN lessons_per_week SET DEFAULT 1;",
            reverse_sql="ALTER TABLE groups ALTER COLUMN lessons_per_week DROP DEFAULT;",
        ),
    ]
