# Generated by Django 5.2.15 on 2026-07-02 10:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


def backfill_slot_effective_from(apps, schema_editor):
    """
    Существующие слоты действуют с даты старта их группы. Где group_start_date
    NULL — оставляем sentinel '2000-01-01' (слот «активен всегда»).
    """
    Group = apps.get_model('groups', 'Group')
    Slot = apps.get_model('groups', 'GroupScheduleSlot')
    for g in Group.objects.exclude(group_start_date__isnull=True).only('id', 'group_start_date'):
        Slot.objects.filter(group_id=g.id).update(effective_from=g.group_start_date)


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonScheduleException',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('original_date', models.DateField(blank=True, null=True)),
                ('original_time', models.TimeField(blank=True, null=True)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('new_start_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson_schedule_exceptions',
                'managed': True,
            },
        ),
        migrations.RemoveConstraint(
            model_name='groupscheduleslot',
            name='group_schedule_slots_group_id_day_of_week_start_time_key',
        ),
        migrations.AddField(
            model_name='groupscheduleslot',
            name='effective_from',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='groupscheduleslot',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='groupscheduleslot',
            index=models.Index(fields=['group', 'effective_from', 'effective_to'], name='gss_group_effective_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupscheduleslot',
            constraint=models.UniqueConstraint(fields=('group', 'day_of_week', 'start_time', 'effective_from'), name='gss_versioned_key'),
        ),
        migrations.AddConstraint(
            model_name='groupscheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='gss_effective_range_check'),
        ),
        migrations.AddField(
            model_name='lessonscheduleexception',
            name='group',
            field=models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='groups.group'),
        ),
        migrations.AddField(
            model_name='lessonscheduleexception',
            name='new_teacher',
            field=models.ForeignKey(blank=True, db_column='new_teacher_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_exceptions_as_new', to='teachers.teacher'),
        ),
        migrations.AddIndex(
            model_name='lessonscheduleexception',
            index=models.Index(fields=['group', 'original_date'], name='lse_group_orig_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonscheduleexception',
            index=models.Index(fields=['group', 'new_date'], name='lse_group_new_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonscheduleexception',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['reschedule', 'cancel', 'extra'])), name='lse_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='lessonscheduleexception',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'cancel'), _negated=True), ('new_date__isnull', True), _connector='OR'), name='lse_cancel_shape_check'),
        ),
        migrations.AddConstraint(
            model_name='lessonscheduleexception',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'reschedule'), _negated=True), models.Q(('original_date__isnull', False), ('new_date__isnull', False)), _connector='OR'), name='lse_reschedule_shape_check'),
        ),
        migrations.AddConstraint(
            model_name='lessonscheduleexception',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'extra'), _negated=True), models.Q(('original_date__isnull', True), ('new_date__isnull', False)), _connector='OR'), name='lse_extra_shape_check'),
        ),
        # Django снимает default на уровне БД после AddField → raw-INSERT слотов
        # (apps/groups/repository.py) без effective_from упал бы. Ставим DB-default
        # (тот же приём, что 0001_initial для groups.created_at/active/…).
        migrations.RunSQL(
            sql="ALTER TABLE group_schedule_slots ALTER COLUMN effective_from SET DEFAULT '2000-01-01';",
            reverse_sql="ALTER TABLE group_schedule_slots ALTER COLUMN effective_from DROP DEFAULT;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lesson_schedule_exceptions ALTER COLUMN created_at SET DEFAULT now();",
            reverse_sql="ALTER TABLE lesson_schedule_exceptions ALTER COLUMN created_at DROP DEFAULT;",
        ),
        # Бэкфилл дат действия существующих слотов из group_start_date.
        migrations.RunPython(backfill_slot_effective_from, migrations.RunPython.noop),
    ]
