# Generated by Django 5.2.15 on 2026-07-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_lessonscheduleexception_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonScheduleException',
        ),
    ]
