# Generated by Django 5.2.15 on 2026-07-06 08:00

import datetime
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_directionevent_direction_insert_insert_and_more'),
        ('groups', '0003_delete_lessonscheduleexception'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('name', models.TextField()),
                ('is_individual', models.BooleanField()),
                ('lesson_duration_minutes', models.IntegerField(default=90)),
                ('lessons_per_week', models.IntegerField(default=1)),
                ('group_start_date', models.DateField(blank=True, null=True)),
                ('vk_chat', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupScheduleSlotEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('effective_from', models.DateField(default=datetime.date(2000, 1, 1))),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='group',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "groups_groupevent" ("active", "created_at", "direction_id", "group_start_date", "id", "is_individual", "lesson_duration_minutes", "lessons_per_week", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "teacher_id", "vk_chat") VALUES (NEW."active", NEW."created_at", NEW."direction_id", NEW."group_start_date", NEW."id", NEW."is_individual", NEW."lesson_duration_minutes", NEW."lessons_per_week", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."teacher_id", NEW."vk_chat"); RETURN NULL;', hash='cedc185df34a6782618d5faf13bea655536a287d', operation='INSERT', pgid='pgtrigger_insert_insert_6026d', table='groups', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='group',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "groups_groupevent" ("active", "created_at", "direction_id", "group_start_date", "id", "is_individual", "lesson_duration_minutes", "lessons_per_week", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "teacher_id", "vk_chat") VALUES (NEW."active", NEW."created_at", NEW."direction_id", NEW."group_start_date", NEW."id", NEW."is_individual", NEW."lesson_duration_minutes", NEW."lessons_per_week", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."teacher_id", NEW."vk_chat"); RETURN NULL;', hash='bcff0288aa94b877548d5aa37c566e2ebeaad88e', operation='UPDATE', pgid='pgtrigger_update_update_02517', table='groups', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='group',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "groups_groupevent" ("active", "created_at", "direction_id", "group_start_date", "id", "is_individual", "lesson_duration_minutes", "lessons_per_week", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "teacher_id", "vk_chat") VALUES (OLD."active", OLD."created_at", OLD."direction_id", OLD."group_start_date", OLD."id", OLD."is_individual", OLD."lesson_duration_minutes", OLD."lessons_per_week", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."teacher_id", OLD."vk_chat"); RETURN NULL;', hash='40be2b3323a27f4d3bd624e6a669c76c49e674e7', operation='DELETE', pgid='pgtrigger_delete_delete_13da0', table='groups', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupscheduleslot',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "groups_groupscheduleslotevent" ("day_of_week", "effective_from", "effective_to", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_time") VALUES (NEW."day_of_week", NEW."effective_from", NEW."effective_to", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start_time"); RETURN NULL;', hash='7363734efc9b62b5a7947421a3123825b1983eb3', operation='INSERT', pgid='pgtrigger_insert_insert_4c329', table='group_schedule_slots', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupscheduleslot',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "groups_groupscheduleslotevent" ("day_of_week", "effective_from", "effective_to", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_time") VALUES (NEW."day_of_week", NEW."effective_from", NEW."effective_to", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start_time"); RETURN NULL;', hash='4f20b5debe78b96492bd63355a7c413ee180a0ef', operation='UPDATE', pgid='pgtrigger_update_update_36bd8', table='group_schedule_slots', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='groupscheduleslot',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "groups_groupscheduleslotevent" ("day_of_week", "effective_from", "effective_to", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_time") VALUES (OLD."day_of_week", OLD."effective_from", OLD."effective_to", OLD."group_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."start_time"); RETURN NULL;', hash='dac3ff44c8a6b4324d95b49e959e320d3e91f4c3', operation='DELETE', pgid='pgtrigger_delete_delete_3c4bb', table='group_schedule_slots', when='AFTER')),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='direction',
            field=models.ForeignKey(db_column='direction_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='directions.direction'),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='groupscheduleslotevent',
            name='group',
            field=models.ForeignKey(db_column='group_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupscheduleslotevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='groupscheduleslotevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='groups.groupscheduleslot'),
        ),
    ]
