# Generated by Django 5.2.15 on 2026-07-21 23:30

import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupevent_groupscheduleslotevent_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='group',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='group',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='group',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='group',
            name='lesson_number_offset',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='lesson_number_offset',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='group',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "groups_groupevent" ("active", "created_at", "direction_id", "group_start_date", "id", "is_individual", "lesson_duration_minutes", "lesson_number_offset", "lessons_per_week", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "teacher_id", "vk_chat") VALUES (NEW."active", NEW."created_at", NEW."direction_id", NEW."group_start_date", NEW."id", NEW."is_individual", NEW."lesson_duration_minutes", NEW."lesson_number_offset", NEW."lessons_per_week", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."teacher_id", NEW."vk_chat"); RETURN NULL;', hash='795749c0ab7c44860cc60db03449797b54d38fde', operation='INSERT', pgid='pgtrigger_insert_insert_6026d', table='groups', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='group',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "groups_groupevent" ("active", "created_at", "direction_id", "group_start_date", "id", "is_individual", "lesson_duration_minutes", "lesson_number_offset", "lessons_per_week", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "teacher_id", "vk_chat") VALUES (NEW."active", NEW."created_at", NEW."direction_id", NEW."group_start_date", NEW."id", NEW."is_individual", NEW."lesson_duration_minutes", NEW."lesson_number_offset", NEW."lessons_per_week", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."teacher_id", NEW."vk_chat"); RETURN NULL;', hash='09d1ca54a7cb00afc914dbea25dd67f4cf6ef15e', operation='UPDATE', pgid='pgtrigger_update_update_02517', table='groups', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='group',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "groups_groupevent" ("active", "created_at", "direction_id", "group_start_date", "id", "is_individual", "lesson_duration_minutes", "lesson_number_offset", "lessons_per_week", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "teacher_id", "vk_chat") VALUES (OLD."active", OLD."created_at", OLD."direction_id", OLD."group_start_date", OLD."id", OLD."is_individual", OLD."lesson_duration_minutes", OLD."lesson_number_offset", OLD."lessons_per_week", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."teacher_id", OLD."vk_chat"); RETURN NULL;', hash='672b12098a3e4933caa5b96e2d90149d2ee57ff7', operation='DELETE', pgid='pgtrigger_delete_delete_13da0', table='groups', when='AFTER')),
        ),
    ]
