# Generated by Django 5.2.15 on 2026-07-27 09:56

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0004_remove_direction_insert_insert_and_more'),
        ('groups', '0005_remove_group_insert_insert_and_more'),
        ('teachers', '0002_teacherevent_teacher_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='group',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='group',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='group',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='group',
            name='lessons_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='lessons_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='group',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "groups_groupevent" ("active", "created_at", "direction_id", "group_start_date", "id", "is_individual", "lesson_duration_minutes", "lesson_number_offset", "lessons_per_week", "lessons_total", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "teacher_id", "vk_chat") VALUES (NEW."active", NEW."created_at", NEW."direction_id", NEW."group_start_date", NEW."id", NEW."is_individual", NEW."lesson_duration_minutes", NEW."lesson_number_offset", NEW."lessons_per_week", NEW."lessons_total", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."teacher_id", NEW."vk_chat"); RETURN NULL;', hash='22891fec2690f1c705f324da9fc96d62362cee0b', operation='INSERT', pgid='pgtrigger_insert_insert_6026d', table='groups', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='group',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "groups_groupevent" ("active", "created_at", "direction_id", "group_start_date", "id", "is_individual", "lesson_duration_minutes", "lesson_number_offset", "lessons_per_week", "lessons_total", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "teacher_id", "vk_chat") VALUES (NEW."active", NEW."created_at", NEW."direction_id", NEW."group_start_date", NEW."id", NEW."is_individual", NEW."lesson_duration_minutes", NEW."lesson_number_offset", NEW."lessons_per_week", NEW."lessons_total", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."teacher_id", NEW."vk_chat"); RETURN NULL;', hash='a311a7f2c59aeec3fe392466936872ad3149d69e', operation='UPDATE', pgid='pgtrigger_update_update_02517', table='groups', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='group',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "groups_groupevent" ("active", "created_at", "direction_id", "group_start_date", "id", "is_individual", "lesson_duration_minutes", "lesson_number_offset", "lessons_per_week", "lessons_total", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "teacher_id", "vk_chat") VALUES (OLD."active", OLD."created_at", OLD."direction_id", OLD."group_start_date", OLD."id", OLD."is_individual", OLD."lesson_duration_minutes", OLD."lesson_number_offset", OLD."lessons_per_week", OLD."lessons_total", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."teacher_id", OLD."vk_chat"); RETURN NULL;', hash='d1f7c1dcfd37ad2d2ea73ef22bed4d82feda542c', operation='DELETE', pgid='pgtrigger_delete_delete_13da0', table='groups', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('lessons_total__isnull', True), ('lessons_total__gt', 0), _connector='OR'), name='groups_lessons_total_check'),
        ),
    ]
